import 'buildpc.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'cartmodel.dart';

class CaseMain extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CaseBody();
  }
}

class CaseBody extends StatefulWidget {
  @override
  _CaseBodyState createState() => _CaseBodyState();
}
final List<String> cases = [
    'Logic Case SC-02A, 3.5" to 2x 2.5" Drive Bay Converter',
    '19" 1U Cable Management Bar, Black                ',
    'Xclio NC-01-BLANK Server 1U Data Cabinet 19" Blanking panel Black        ',
    "ScanFX Mining Case Aluminum Open Air Free Standing for upto 8 GPU's and 5 x 120mm Fans and upgradable to rack & stack    ",
    'Cooler Master Vertical GPU Holder & Riser Cable, 1 GPU per Holder, 7 PCI Case Slots Required, Dark Metallic Grey         ',
    'SilverStone 5.25" Front Panel Multi-functional Internal Card Reader, LCD Displays, 1x USB 3.1 Gen1 C, 2x USB 3.1 Gen1 A  ',
    'Silverstone ES02-USB 2.4GHz Wireless Eemote PC power/reset switch, USB 2.0 9-Pin interface              ',
    'NZXT HUE 5.25" RGB Color Changing LED Controller 5.25" Bay                                                        ',
    'Xclio 3.5" Internal All in One Memory Card Reader, MS/MS Duo, SD/MMC, CF, XD, T-Flash, M2, USB2.0, Black               ',
    '5U Intel SC5600LX Server Chassis, 10x SAS/SATA Bays, Black ',
    'SuperO SC835TQ-R800B Case        ',
    'In-Win IW-PLG, Multi GPU Workstation Server Tower Chassis, 1200W PSU, ATX/CEB/EEB  ',
    'Supermicro SC745TQ-R800 Black Case Server Case Rack/Tower with 800W Redundant PSU           ',
    'Supermicro SuperChassis 743TQ-1200B-SQ, Black, 4U Tower Chassis, E-ATX/ATX, 8x 3.5" Hotswap, 3x 5.25", 1200W Plat. PSU   ',
    '5.2U Pedestal, SC5650BRP,ï¿½Intel 5500, 1366 x2, PCI-E 2.0 (x8), DDR3 1333 ECC, Reg/ Unbuffered Memory    ',
    'Intel SC5600BASE, 5U Pedestal Server Case, Black, 6x 3.5" and 3x 5.25" Bays, 670W PSU, 120mm Fan ',
    'SilverStone CS350B Storage Case with 5x 3.5" Hot-Swap SAS/SATA HDD Bays, Rackmount/Destkop, Black, 2xUSB3.0, ATX         ',
    'In-Win IW-MS08 Server Chassis, 8x Hot-Swap Bays,12Gbps MiniSAS, 4 Full-Size PCI-e Slots, MicroATX/Mini ITX           ',
    'SuperO CSE-813MFT-300CB Case                ',
    'Supermicro Chassis 1U Standard i/o 203W, 2x 2.5" Hot Swap SAS/SATA HDD Bays, 1x LP PCI Expansion slot, Black  ',
    'Supermicro SuperChassis Compact Mini-Tower, 4x 3.5"/2.5" Drive Bays, 250w 80PLUS Bronze PSU, 1x Slim ODD, mITX     ',
    'Supermicro 732i-500B Server Chassis, 4x 3.5" SAS/SATA Drive Bays, 2x 5.25" Drive Bays, Upto E-ATX, 2x USB 2.0, 500w PSU  ',
    'In-Win IW-MS04-01 Black Mini-ITX NAS Storage Server Chassis, with 4x 2.5"/3.5" SATA3 Hot Swap Drive Bays, 265W Flex PSU  ',
    'In-Win IW-PE052, Midi Tower Server Chassis, ATX/CEB  ',
    'Cooler Master Vertical GPU Holder & Riser Cable, 1 GPU per Holder, 7 PCI Case Slots Required, Dark Metallic Grey         ',
    'SilverStone 5.25" Front Panel Multi-functional Internal Card Reader, LCD Displays, 1x USB 3.1 Gen1 C, 2x USB 3.1 Gen1 A  ',
    'Silverstone ES02-USB 2.4GHz Wireless Eemote PC power/reset switch, USB 2.0 9-Pin interface              ',
    'NZXT HUE 5.25" RGB Color Changing LED Controller 5.25" Bay                                                        ',
    'Xclio 3.5" Internal All in One Memory Card Reader, MS/MS Duo, SD/MMC, CF, XD, T-Flash, M2, USB2.0, Black               ',
    'Orion 24U Acoustic Rack , 600W x 800D x 1320H, Black      ',
    'APC NetShelter Deep Rack Enclosure SX 42U with Black Sides, 600mm Wide x 1200mm Deep, 19" Rack Width            ',
    'NetShelter SX 48U 600mm Wide x 1070mm Deep Enclosure with Sides Black             ',
    'Dynamode 42U 19" 800x1200 Floor Standing Server Cabinet / Rack            ',
    'Dynamode 47U 19" 800x1000 Floor Standing Server Cabinet / Rack             ',
    'Dynamode 47U 19" 800x800 Floor Standing Data / Comms Cabinet / Rack          ',
    'Dynamode 47U 19" 600x800 Floor Standing Data / Comms Cabinet / Rack             ',
    'Dynamode 47U 19" 600x1000 Floor Standing Server Cabinet / Rack           ',
    'Dynamode 42U 19" 800x1000 Floor Standing Server Cabinet / Rack                             ',
    'Dynamode 47U 19" 600x600 Floor Standing Data / Comms Cabinet / Rack          ',
    'Dynamode 42U 19" 800 x 800 Floorstanding Cabinet                      ',
    'Dynamode 27U 19" 800x1000 Floor Standing Server Cabinet / Rack              ',
    'Dynamode 42U 19" 600x1000 Floor Standing Server Cabinet / Rack                  ',
    'Dynamode 42U 19" 800x600 Floorstanding Data / Comms Cabinet / Rack           ',
    'Dynamode 36U 19" 800 x 800 Floorstanding Network Cabinet          ',
    'Dynamode 27U 19" 800x800 Floor Standing Data / Comms Cabinet / Rack          ',
    'Dynamode 27U 19" 600x1000 Floor Standing Server Cabinet / Rack          ',
    'Dynamode 36U 19" 600 x 800 Floorstanding Network Cabinet           ',
    'Dynamode 42U 19" 600x600 Floor Standing Data / Comms Cabinet / Rack          ',
    'Dynamode 27U 19" 600x800 Floor Standing Data / Comms Cabinet / Rack        ',
    'Dynamode 36U 19" 600 x 600 Floorstanding Network Cabinet             ',
    'Dynamode 22U 19" 600x800 Floor Standing Data / Comms Cabinet / Rack              ',
    'Dynamode 27U 19" 600x600 Floor Standing Data / Comms Cabinet / Rack           ',
    'Dynamode 18U 19" 600x800 Floor Standing Data / Comms Cabinet / Rack                 ',
    'Dynamode 22U 19" 600x600 Floor Standing Data / Comms Cabinet / Rack           ',
    'Dymamode 18U 19" 600x600 Floor Standing Data / Comms Cabinet / Rack                 ',
    'LMS Data 20U 600 x 600 Deep, Floor Standing 19 Inch Rackmount Cabinet - ValuCab      ',
    '18U 19" 550mm deep Wall Mount Cabinet, Black             ',
    'Dynamode CAB-W12U-EL550 12U Wall Mount Cabinet 550mm Deep                       ',
    '15U Dynamode CAB-W15U-EL550 19" 550mm deep Wall Mount Cabinet - Black                  ',
    'ScanFX NCOH-27-60-60 27U Four Post Open Frame 600x600mm for 19" Rackmount Devices              ',
    'Dynamode CAB-W9U-EL550 9U 19" Wall Mount Cabinet 550mm Deep Black                       ',
    'LMS Data CAB-W12U-EL450 12U 19" Wall Mount Cabinet 450mm Deep Black              ',
    'LMS Data CAB-W9U-EL450 9U 19" Wall Mount Cabinet 450mm Deep Black             ',
    'LMS Data 12U 19" 550x450mm Deep Wall Cabinet, Flatpack, Black     ',
    'ScanFX NCOH-18-60-60 18U Four Post Open Frame 600x600mm  for 19" Rackmount Devices              ',
    'LMS Data 9U 19" 550x450mm Deep Wall Cabinet, Flatpack, Black      ',
    'LMS Dtata 19" 550mm 9U Server Wall Mount Cabinet, Lockable Glass Front Door, Vented Shelf, Grey ',
    'LMS Data CAB-W6U-EL550 6U 19" Wall Mount Cabinet 550mm Deep Black             ',
    'Dynamode CAB-WFP-FE-6U450 Eco Line cabinet - 450mm deep - lockable glass door, fixed sides            ',
    'Dynamode 6U CAB-W6U-EL450 Wallmounting Rack Cabinet, 450mm deep, Black, Lockable Glass Door      ',
    'LMS Data 6U 19" 550x450mm Deep Wall Cabinet, Flatpack, Black     ',
    'LMS Data CAB-DRW-FE-3U 19" Rackmount 3U Lockable Draw for Server Cabinets  ',
    'LMS Data 19" Fixed Vented Shelf for 1000mm Deep Cabinets (W)465x(D)700x(H)15mm for Eco NetCab Range Server Cabinets  ',
    'LMS Data 19" Fixed Vented Shelf for 800mm Deep Cabinets (W)465x(D)500x(H)15mm for Eco NetCab Range Server Cabinets   ',
    'LMS Data Fixed Vented Shelf for 1000mm Deep Cabinets cabinets (EcoNetcab)  (W)489 X (D)700 X (H)15mm     ',
    'LMS Data 19" Fixed Vented Shelf for 600mm Deep Cabinets (W)465x(D)305x(H)15mm for Eco NetCab Range Server Cabinets       ',
    'Thermaltake Tempered Glass Side Panel for Core P3',
    'NZXT HUE 2 Ambient Underglow Lighting for E-ATX/ATX cases, 2x 300mm Strips, NZXT CAM Software Control                    ',
    'Thermaltake Tt Sync Controller TT Premium Ed. 9-Port Hub for Syncing Addressable LEDs w/ ASUS/GIGABYTE/MSI Motherboards  ',
    'NZXT HUE 2 Ambient Underglow Lighting for mATX/ITX cases, 2x 200mm Strips, NZXT CAM Software Control                     ',
    'SilverStone G11313530-RT - USB Type C, USB3.1 Gen.2, Upgrade kit for SilverStone Chassis       ',
    'Obsidian Series 750D USB 3.1 Type C I/O Panel Upgrade Kit          ',
    'MSI ATLAS MYSTIC V2.0 Graphics Card Support, ARGB, Acrylic, Upto 7.5KG Weight, Mystic Light Sync         ',
    'be quiet! Dark Base PRO 900 PSU Shroud - compatible Dark Base 900 also                             ',
    'Silverstone ES02-USB 2.4GHz Wireless Eemote PC power/reset switch, USB 2.0 9-Pin interface              ',
    'NZXT HUE 2 RGB Advanced LED Lighting Extension Kit, 2x 300mm, 10-LEDs Per Strip                                        ',
    'Fractal Design Connect D1 USB3.1 Gen 2 Speeds up to 10 Gbps, USB Fast charging support,  Reversible USB Type-C port      ',
    'Corsair Obsidian Series 750D Front Panel High Airflow Intake Kit - CC-8930331                          ',
    'NZXT Puck Red - Cable Tidy, Headset Holder, Magnetic Mount, PC Case Accessory                  ',
    'NZXT Puck Purple - Cable Tidy, Headset Holder, Magnetic Mount, PC Case Accessory                  ',
    'NZXT Puck PC Case Headset Mount and Cable Management, White                                               ',
    'NZXT Puck PC Case Headset Mount and Cable Management, Black                                           ',
    'NZXT Puck Blue - Cable Tidy, Headset Holder, Magnetic Mount, PC Case Accessory                           ',
    'Silverstone RA02B Durable Rackmount Ear Kit GD07, GD08, Black                       ',
    'DEEPCOOL A-RGB Remote Controller, 3-Pin ARGB, 4 Button, IR Remote  ',
    'Silverstone CA02 Screw Pack, Case screws, Washers and cable ties                           ',
    'Fractal Design HDD Tray Kit Type-B, Dual Pack, 2x 3.5ï¿½/2.5ï¿½ HDD/SSD Trays, Thumbscrews, Black         ',
    'DEEPCOOL GH-01 Graphics Card Support, Adjustable, ARGB, Base Extension Included, Supports Cases With/Without PSU Shroud  ',
    'Corsair HDD Upgrade Kit with 3x HDD Trays + HDD Cage Parts, for Graphite 600T/730T/760T/780T, Obsidian 450D/650D/750D    ',
    'Fractal Design Universal Multibracket Dual Pack, Type-A, 2.5ï¿½/3.5ï¿½ SSD/HDD Compatibility, Black        ',
    'Fractal Design SSD Bracket Kit, Type-B, Dual Pack, 2x 2.5ï¿½ SSD Brackets, Thumbscrews, White          ',
    'Fractal Design SSD Bracket Kit, Type-B, Dual Pack, 2x 2.5ï¿½ SSD Brackets, Thumbscrews, Black       ',
    'Fractal Design HDD Tray Kit Type-B, Dual Pack, 2x 3.5ï¿½/2.5ï¿½ HDD/SSD Trays, Thumbscrews, White       ',
    'Fractal Design Define 7 HDD Cage Upgrade Kit, Type-B, Black        ',
    'Silverstone SST-MVA01 VESA Extension Bracket, Enables Mounting of NUC with Monitor Arm, 75x75mm / 100x100mm, 2.0mm SECC  ',
    'be quiet! BGA05 Hard Drive Cage - compatible with Dark Base PRO 900, Dark Base 900, Dark Base 700                        ',
    'AsRock Vesa Mount for Deskmini - VESA 75x75mm or 100x100mm mount.               ',
    'Corsair 750D Top Panel Mesh Filter - CC-8930186                     ',
    'Silverstone SST-Aeroslots, Vented Slot covers, 4 pcs., Nickel-coated                       ',
    'Corsair 750D Front and Bottom Replacement Dust Filter - CC-8930174                 ',
    'be quiet! HDD Slot Cover compatible with PB600/DB900                           ',
    'Supermicro MCP-220-00044-0N, Retention Bracket for up to 2x 2.5" HDD Silver                            ',
    'Corsair Carbide 678C HDD Access Cover, Black\t\t\t\t\t\t\t\t\t\t\t            ',
    'Jou-Jye VESA Kit for NU-0526, NU-0528 and NU-0568         ',
    'Thermalright Socket 2011 Retention Kit Compatible with HR-02 Macho, True Spirit 120, True Spirit 140               ',
    'Silverstone G11902311 Accessory Package FT03           ',
    'Corsair Lighting Node Pro, RGB Lighting Controller with 4x Individually Addressable RGB LED Strips                       ',
    'Cooler Master Vertical GPU Holder & Riser Cable, 1 GPU per Holder, 7 PCI Case Slots Required, Dark Metallic Grey         ',
    'SilverStone 5.25" Front Panel Multi-functional Internal Card Reader, LCD Displays, 1x USB 3.1 Gen1 C, 2x USB 3.1 Gen1 A  ',
    'Silverstone ES02-USB 2.4GHz Wireless Eemote PC power/reset switch, USB 2.0 9-Pin interface              ',
    'NZXT HUE 5.25" RGB Color Changing LED Controller 5.25" Bay                                                        ',
    'Xclio 3.5" Internal All in One Memory Card Reader, MS/MS Duo, SD/MMC, CF, XD, T-Flash, M2, USB2.0, Black               ',
    'Akasa Pascal MD, 6th and 7th Gen Intel NUC Board Case, IP65, Ultra Compact, Fanless     ',
    'Akasa Pascal BC, 8th Gen Intel NUC (Bean Canyon) Board Case, IP65, Ultra Compact, Fanless       ',
    'Cooler Master MasterCase NC100, Black, Small Form-Factor Chassis w/ VGold SFX PSU, 2x 92mm Fans, USB 3.1 Gen 2 Type-A    ',
    'Akasa Turing FX NUC for Intel 10th Gen up to i7 (Frost Canyon), Fanless Case, 2.5" HDD/SSD, USB A+C, Kensington Lock    ',
    'Akasa Plato PX, Slim Fanless Case for 8th Gen Intelï¿½ NUC i3/i5/i7 Boards (Provo Canyon), USB 3.0/2.0, Kensington Lock    ',
    'Akasa Turing A-NUC45-M1B Compact Fanless Case, Aluminium, 8th Generation Intel Bean Canyon NUC, UCFF 4x4 Inch         ',
    'Akasa PlatoX8 Fanless Case for Intel NUC 8th Gen, UFCC 4x4, 2.5" SSD/HDD, Supports Intel i3, i5, i7 CPU`s, Aluminium, B  ',
    'Akasa Newton PX, Fanless Case, for 8th Generation Intelï¿½ NUC i3/i5 Boards (Provo Canyon), USB 3.0/2.0, Kensington Lock   ',
    'Akasa Plato X7D Fanless Low Profile Case, 7th Generation Intel NUC Dawson Canyon, 2.5" HDD/SSD, 2x USB 2.0/2x USB 3.0    ',
    'Akasa Plato X7 Fanless case for NUC7i5/i3 Supports 2.5" HDD/SSD with front I/O Ports, Aluminum                ',
    'Akasa Plato X Slim Fanless Chassis for 5th Generation Intel NUC Core i7/i5/i3 Boards, USB 3.0, Serial Port, 2.5" Bay     ',
    'Akasa Newton S7 Aluminum Fanless case for NUC7i5/i3 Supports 2.5" HDD/SSD with front I/O Ports                   ',
    'Akasa Newton S Fanless Intel NUC Case, w/ Serial Port, 2.5" SSD Bay, VESA Mount, for 5th gen Rock/Maple Canyon NUC board ',
    'Akasa Newton S7D Fanless Low Profile Case, 7th Generation Intel NUC Dawson Canyon, 2.5" HDD/SSD, 2x USB 2.0/2x USB 3.0   ',
    'Akasa Newton JC Fanless Low Profile Case, 8th Generation Intel NUC June Canyon, 2.5" HDD/SSD       ',
    'Akasa Newton D3 Fanless Low Profile Case, 7th Generation Intel NUC Dawson Canyon, 2x 2.5" HDD/SSD, 2x USB 3.0         ',
    'Akasa Newton AC, Fanless Ali case for Intel NUC (Board Specific)+2.5" HDD/SSD, with VGA support            ',
    'Akasa 1U Rackmount front plate for Plato X7D          ',
    '1U Akasa Rackmount front plate for Plato, Plato X, Plato X6          ',
    'Silverstone SST-PT15B-H2 Petit Intel NUC                 ',
    'Silverstone SST-PT15B-H1D1 Petit Intel NUC                 ',
    "ScanFX Mining Case Aluminum Open Air Free Standing for upto 8 GPU's and 5 x 120mm Fans and upgradable to rack & stack    ",
    'Cooler Master Vertical GPU Holder & Riser Cable, 1 GPU per Holder, 7 PCI Case Slots Required, Dark Metallic Grey         ',
    'SilverStone 5.25" Front Panel Multi-functional Internal Card Reader, LCD Displays, 1x USB 3.1 Gen1 C, 2x USB 3.1 Gen1 A  ',
    'Silverstone ES02-USB 2.4GHz Wireless Eemote PC power/reset switch, USB 2.0 9-Pin interface              ',
    'NZXT HUE 5.25" RGB Color Changing LED Controller 5.25" Bay                                                        ',
    'Xclio 3.5" Internal All in One Memory Card Reader, MS/MS Duo, SD/MMC, CF, XD, T-Flash, M2, USB2.0, Black               ',
    'NZXT H1, White, Mini ITX Chassis w/ Tempered Glass Window, 140mm AIO, USB 3.1 Gen2 Type-C, mITX, 650W 80 PLUS Gold PSU   ',
    'NZXT H1, Black, Mini ITX Chassis w/ Tempered Glass Window, 140mm AIO, USB 3.1 Gen2 Type-C, mITX, 650W 80 PLUS Gold PSU   ',
    'Akasa Crypto VESA Media Black mini-ITX Case with 80W PSU - Perfectly Mounts on Vesa Monitors                             ',
    'CiT S003B, Black, Slim Micro-ATX Case, 1x 80mm Fan, 2x USB 2.0, 300W PSU, mATX/mITX       ',
    'CiT SO14B, Black, Slim micro-ATX Case with 3-in-1 Card Reader, 80mm Fan, USB3.0, with 300W PSU                           ',
    'CiT Phaser Gaming Computer Chassis, 1x USB 3.0, 3x USB 2.0, 1x 92mm Exhaust Fan, with 500W PSU, Black                    ',
    'CiT Classic PC Chassis + Power Supply, 500W Single Rail PSU, 1x 80mm Fan Included, MicroATX/MiniITX, USB 3.0             ',
    'CiT MX-A05, Black, Micro ATX Chassis, 1x 80mm Fan, 1x USB 3.0, 2x USB 2.0, 500W PSU, Cable Management, mATX/mITX         ',
    'Fractal Design Node 202 Mini-ITX Computer Chassis with Built-In 450W Fractal SFX PSU, Horizontal/Vertical Orientation    ',
    'Antec ISK110 Mini ITX PC Case, 2x 2.5" Drive Bays, 2x USB 3.0/2.0, 90w PSU, VESA Mountable, mITX                         ',
    'In-Win IW-MS04-01 Black Mini-ITX NAS Storage Server Chassis, with 4x 2.5"/3.5" SATA3 Hot Swap Drive Bays, 265W Flex PSU  ',
    'Cooler Master Vertical GPU Holder & Riser Cable, 1 GPU per Holder, 7 PCI Case Slots Required, Dark Metallic Grey         ',
    'SilverStone 5.25" Front Panel Multi-functional Internal Card Reader, LCD Displays, 1x USB 3.1 Gen1 C, 2x USB 3.1 Gen1 A  ',
    'Silverstone ES02-USB 2.4GHz Wireless Eemote PC power/reset switch, USB 2.0 9-Pin interface              ',
    'NZXT HUE 5.25" RGB Color Changing LED Controller 5.25" Bay                                                        ',
    'Xclio 3.5" Internal All in One Memory Card Reader, MS/MS Duo, SD/MMC, CF, XD, T-Flash, M2, USB2.0, Black               ',
    'NZXT H1, White, Mini ITX Chassis w/ Tempered Glass Window, 140mm AIO, USB 3.1 Gen2 Type-C, mITX, 650W 80 PLUS Gold PSU   ',
    'NZXT H1, Black, Mini ITX Chassis w/ Tempered Glass Window, 140mm AIO, USB 3.1 Gen2 Type-C, mITX, 650W 80 PLUS Gold PSU   ',
    'Streacom ST-DB4, Silver, Compact Fanless Case, Aluminium, Bi-Symmetrical Chassis, Mini-ITX, USB 3.0       ',
    'Streacom ST-DB4, Black, Compact Fanless Case, Aluminium, Bi-Symmetrical Chassis, Mini-ITX, USB 3.0          ',
    'ASUS ROG Z11, Black, MiniITX Chassis w/ Tempered Glass Window, RGB, 3x 140mm Fans, USB 3.2 Gen 2 Type-C, mITX/mDTX      ',
    'Streacom DA2 Silver Full Aluminium Compact ITX Computer Case, Mini ITX, 6x 3.5"/2.5", Dual Slot GPU           ',
    'Streacom DA2 Black Full Aluminium Compact ITX Computer Case, Mini ITX, 6x 3.5"/2.5", Dual Slot GPU ATX/SFX PSU           ',
    'Akasa Maxwell Pro, Aluminum Fanless Case, Supports 65W TDP CPU, Supports Mini-ITX Boards      ',
    'Akasa 1U Galileo TU3, Fanless Slim Thin Mini ITX Case, 4x 2.5" SSD/HDD and PCIe slot support, Optional               ',
    'Fractal Design Era ITX, Titanium Grey, Compact Chassis w/ Walnut Top Panel, 80mm Fan, USB 3.1 Gen2 Type-C, Mini-ITX      ',
    'Fractal Design Era ITX, Silver, Compact Chassis w/ White Oak Top Panel, 80mm Fan, USB 3.1 Gen2 Type-C, Mini-ITX          ',
    'Fractal Design Era ITX, Gold, Compact Chassis w/ Tempered Glass Top Panel, 80mm Fan, USB 3.1 Gen2 Type-C, Mini-ITX       ',
    'Fractal Design Era ITX, Cobalt, Compact Chassis w/ Tempered Glass Top Panel, 80mm Fan, USB 3.1 Gen2 Type-C, Mini-ITX     ',
    'Fractal Design Era ITX, Carbon, Compact Chassis w/ Tempered Glass Top Panel, 80mm Fan, USB 3.1 Gen2 Type-C, Mini-ITX     ',
    '8 Bay Silverstone DS380B Premium Small Form Factor NAS Case with 3 Fans 3.5"/2.5" HDD/SSD SATA/SAS w/o PSU (SFX)         ',
    'SilverStone Fortress FTZ01B-E High End Small Form Factor Chassis, Aluminium/Steel, Mini ITX/DTX, ATX PSU Compatible      ',
    'Streacom FC8WS ALPHA Silver Fanless Home Theatre Aluminium Chassis (No Optical Drive)                    ',
    'Silverstone SST-LD03B-AF SFF Case, Tempered Glass Panels, Mini-DTX / Mini-ITX, Includes 2x 120mm Fans, Black     ',
    'NZXT H210i, Black/Red, mITX Chassis w/ Glass Window, RGB, Smart Control, 2x 120mm Fans, USB 3.1 Gen2 Type-C, Mini-ITX    ',
    'NZXT H210i, Black, Mini-ITX Chassis w/ Glass Window, RGB, Smart Control, 2x 120mm Fans, USB 3.1 Gen2 Type-C, Mini-ITX    ',
    'Antec Cube EKWB Edition Mini ITX Gaming Case, Lean forward design 350mm GPU, 2x USB 3.0, mITX                            ',
    'SilverStone SST-SG14B Sugo 14 Mini-ITX SFF Cube Chassis, Modular Design, USB 3.0 x 2, USB 2.0, Full length GPU Support   ',
    'SilverStone RVZ03B-ARGB, Black, Mini ITX Computer Chassis, 2x 120mm Fans, ARGB Light Strip, 2x USB 3.0, mITX/mDTX   ',
    'SilverStone RVZ03 RAVEN Z Black Mini ITX Computer Chassis, Mini-ITX/Mini-DTX, with RGB Light Strip, 2x 120mm Fans, USB3  ',
    'Silverstone ML04B-C Milo, Black, Slim HTPC Case, USB 3.0, USB Type-C, Micro-ATX/Mini-DTX/Mini-ITX, w/o PSU        ',
    'SilverStone Lucid LD03B Mini Gaming Chassis, Tempered Glass, 2x 120mm Fans, USB 3.0, Mini-ITX/Mini-DTX          ',
    'Cooler Master MasterBox NR200P, White, Mini Tower w/ Tempered Glass Window, 2x 120mm Fans, USB 3.2 Gen1, mITX/mDTX       ',
    'Cooler Master MasterBox NR200P, Black, Mini Tower w/ Tempered Glass Window, 2x 120mm Fans, USB 3.2 Gen1, mITX/mDTX       ',
    'Streacom F1CWS EVO Silver Mini Aluminium HTPC Chassis, Non Optical Edition, 3x 2.5" HDD Bays, Mini ITX Compatible        ',
    'Silverstone SST-ML08B-H Milo Black Mini ITX Chassis w/ Handle, Black, 2x USB 3.0, 2x 2.5" Drive Bays, 2x Expansion Slots ',
    'NZXT H210, White, Mini-ITX Computer Chassis w/ Tempered Glass Window, 2x 120mm Fans, USB 3.1 Gen2 Type-C, Mini-ITX       ',
    'NZXT H210, Black/Red, Mini-ITX Computer Chassis w/ Tempered Glass Window, 2x 120mm Fans, USB 3.1 Gen2 Type-C, Mini-ITX   ',
    'Fractal Design Node 304, White, Mini-ITX Chassis, 1x 140mm Fan, 2x 92mm Fans, 2x USB 3.0, mATX/mDTX, w/o PSU        ',
    'Silverstone Raven Z Computer Chassis, mDTX/mITX, 2x USB 3.0, w/o PSU, Black                          ',
    'Fractal Design Node 202 Mini-ITX Computer Chassis, Horizontal/Vertical Orientation, Max.310mm GPU, USB 3.0, Black SFX    ',
    'Silverstone ML08B Milo Black Mini ITX Chassis, Black, 2x USB 3.0, 2x 2.5" Drive Bays, 2x Expansion Slots SFX             ',
    'Silverstone SST-ML10B Milo 10 Compact Mini-ITX Case, Modular Design, 2x USB3.0, VESA Mounting Plate    ',
    'Silverstone ML06B USB 3.0 Milo Slim HTPC Case, mini-ITX, w/o PSU (SFX)                                   ',
    'Silverstone Milo Mini ITX Case, 1x 120mm Fan, 2x USB 3.0, Includes Multipurpose 4-in-1 bracket, Black           ',
    'Fractal Design Define Nano S, Black, Mini-ITX Computer Chassis, 140/120mm Dynamic Series Fans, Quiet Design, 2x USB 3.0  ',
    'Fractal Design Define Nano S, Black, Mini ITX Computer Chassis /w Window, 1x 140mm Fan, 1x 120mm Fan, 2x USB 3.0         ',
    'AKASA Cypher Ultra Compact Thin mini-ITX case with 120W PSU     ',
    'Cooler Master MasterCase H100, Black, Mini Tower, 1x 200mm ARGB Fan, 2x USB 3.2 Gen 1, Mini-ITX             ',
    'Fractal Design Core 500 Mini-ITX Cube Case with ATX PSU Support, Black, 1x Silent Series R3 140mm Fan Inc                ',
    'Cooler Master MasterCase H100, Black, Mini-ITX Computer Chassis, mITX, Built-In Handle, 200mm RGB Fan, 2x USB 3.2 Gen1 A ',
    'Cooler Master MasterBox MB320L ARGB, Tempered Glass, 2x 120mm Fans, Radiator Support, MicroATX/Mini-ITX           ',
    'SilverStone PT13B-USB3.0 Petit Thin Mini-ITX Silent Computer Case, Black with Vertical Holder, VESA, 2xUSB3.0            ',
    'Thermaltake Core V1 Black Edition Mini-ITX Cube Case with Window, 1x 200mm Fan Included, USB 3.0, w/o PSU                ',
    'Silverstone Sugo SG13B Cube Mini-ITX/DTX Case (ATX PSU)                                            ',
    'Silverstone SG13WB White Sugo SFF Mini ITX Case, Mesh Front Panel, USB 3.0, Mini DTX/Mini ITX                          ',
    'Silverstone SG05BB-Lite USB 3.0 Sugo SFF mini-ITX Case All Black 120mm Silent Fan w/o PSU (SFX)                          ',
    'Silverstone ML05B USB 3.0, Milo Slim HTPC, mini-ITX, Black, w/o PSU                                    ',
    'Silverstone SG05W-Lite USB 3.0 Sugo SFF mini-ITX, White, Internal Black, w/o PSU (SFX)                                 ',
    'Akasa Cypher MX, VESA, Media, Black, mini-ITX Case, Ultra Compact 2L, 4x USB2.0, VESA Mountable              ',
    'Antec Striker, White, Open Frame Mini-Tower PC Chassis w/ Tempered Glass Windows, USB 3.1 Type-C, Mini-ITX               ',
    'NZXT H210i, White, Mini-ITX Chassis w/ Glass Window, RGB, Smart Control, 2x 120mm Fans, USB 3.1 Gen2 Type-C, Mini-ITX    ',
    'NZXT H210, Black, Mini-ITX Computer Chassis w/ Tempered Glass Window, 2x 120mm Fans, USB 3.1 Gen2 Type-C, Mini-ITX       ',
    'Fractal Design Node 304, Black, Mini-ITX Case, 1x 180mm Fan, 2x 92mm Fans, USB 3.0, Mini ITX/Mini DTX, w/o PSU          ',
    'Thermaltake Core V1 White Snow Edition Mini-ITX Cube Case with Window, 1x 200mm Fan Included, USB 3.0, w/o PSU           ',
    "ScanFX Mining Case Aluminum Open Air Free Standing for upto 8 GPU's and 5 x 120mm Fans and upgradable to rack & stack    ",
    'Cooler Master Vertical GPU Holder & Riser Cable, 1 GPU per Holder, 7 PCI Case Slots Required, Dark Metallic Grey         ',
    'Thermaltake Versa H21 Mid Tower Computer Chassis, ATX/mATX, 1 x USB 3.0, 1 x 120mm rear exhaust fan, Black               ',
    'SilverStone 5.25" Front Panel Multi-functional Internal Card Reader, LCD Displays, 1x USB 3.1 Gen1 C, 2x USB 3.1 Gen1 A  ',
    'Silverstone ES02-USB 2.4GHz Wireless Eemote PC power/reset switch, USB 2.0 9-Pin interface              ',
    'NZXT HUE 5.25" RGB Color Changing LED Controller 5.25" Bay                                                        ',
    'Xclio 3.5" Internal All in One Memory Card Reader, MS/MS Duo, SD/MMC, CF, XD, T-Flash, M2, USB2.0, Black               ',
    'SilverStone SST-CS381 Mid Tower MicroATX/Mini-DTX/Mini-ITX, 2x120mm Fans, 8x 2.5"/3.5" Hot Swap Bays, 2x USB3.1       ',
    '8 Bay Silverstone DS380B Premium Small Form Factor NAS Case with 3 Fans 3.5"/2.5" HDD/SSD SATA/SAS w/o PSU (SFX)         ',
    'Silverstone GD05B, Black, HTPC Desktop Case, 3x 120mm Fans, 2x USB 3.0, Micro-ATX/Mini-DTX/Mini-ITX, w/o PSU   ',
    'Fractal Design Node 804, Black, Micro-ATX Cube Case /w Side Window, 3x 120mm Silent Series R2 Fans, mATX/mITX, w/o PSU   ',
    'Fractal Design Meshify C Mini Dark TG, MicroATX Tower Computer Chassis, w/ Tempered Glass Window, mATX/mITX, 2x120mm Fan ',
    'SilverStone SG12B Sugo Series Black Micro ATX Case, Small Form Factor                              ',
    'SilverStone RL08 Computer Chassis, with Tempered Glass Window, MicroATX/Mini-DTX/Mini-ITX, 2x120mm RGB Fans, Black/White ',
    'Silverstone TJ08B-E Temjin Evolution, Black, Micro-ATX Mini Tower Case, 1x 180mm Fan, 2x USB 3.0 w/o PSU ATX      ',
    'SilverStone Lucid LD01, Black, Mini Tower Chassis /w Tempered Glass Window, 2x USB 3.0, Micro-ATX/Mini-DTX/Mini-ITX   ',
    'Silverstone ML04B Milo, Black, Slim HTPC Case, 2x USB 3.0, Micro-ATX/Mini-DTX/Mini-ITX, w/o PSU      ',
    'Fractal Design Define Mini C TG, MicroATX Computer Chassis, with Tempered Glass Window, MicroATX/Mini-ITX, 2x 120mm Fans ',
    'Cooler Master Silencio S400, Black, MicroATX PC Case, with Sound-Dampened Steel Panels, MicroATX/Mini-ITX, 2x 120mm Fans ',
    'Silverstone SG02B-F USB 3.0, Sugo SFF Cube micro-ATX/ITX, Black, w/o PSU                                            ',
    'Fractal Design Define Mini C Micro ATX Computer Chassis, mATX/mITX, w/ Sound Damping, ModuVent Technology, 2x120mm Fans  ',
    'Silverstone Sugo SG11B Black Small Form Factor micro-ATX/ITX Computer Chassis, with USB 3.0 + Support for Long GPUs      ',
    'Thermaltake V150, Black, Micro Case w/ Tempered Glass Window, 120mm Fan, USB 3.0, mATX/mITX      ',
    'SilverStone Precision PS15B RGB Gaming Chassis, Tempered Glass, 120mm/2x 120mm RGB Fans, USB 3.0, MicroATX      ',
    'Silverstone Precision PS07B USB 3.0 Tower Micro-ATX Case with USB 3.0 w/o PSU                                       ',
    'Silverstone KL06B Kublai Black Micro-ATX/ITX Mini Tower Case w/o PSU (Std ATX)                           ',
    'Nanoxia Deep Silence 4 Black Low Noise Micro-ATX PC Case, 2x 120mm Fans, 2x USB 3.0, Micro-ATX/Mini-ITX      ',
    'GameMax Mini Abyss, Black, MicroATX Chassis w/ Tempered Glass Window, 120mm ARGB Fan, USB 3.0, MicroATX/Mini-ITX         ',
    'Cooler Master MasterBox NR400 (w/o ODD), Black, MicroATX PC Case, w/ Tempered Glass Window, mATX/mITX, 2x 120mm Fans     ',
    'Thermaltake Core V21, Black, Micro-ATX Mesh Stackable Cube PC Chassis /w Window, 1x 200mm Fan, 2x USB 3.0, mATX/mITX     ',
    'Tecware Forge M ARGB, Black, MicroATX Tower w/ Tempered Glass Window, 4x 120mm Fans, USB 3.0, mATX/mITX      ',
    'SilverStone SST-PS15W-G - Precision Mini Tower Micro ATX,Computer Case, Tempered Glass, White, 2xUSB3.0         ',
    'Corsair Carbide Series 88R Windowed MicroATX/MiniITX Computer Chassis, with USB 3.0, Black                               ',
    'Fractal Design Focus G Mini, MicroATX Computer Chassis, MicroATX/Mini-ITX, with Window, 2x 120mm White LED Fans, USB 3.0 ',
    'SilverStone PS15B-G, Black, MicroATX Chassis with Window, 120mm Fan, Headphone, Mic In, 2xUSB 3.0              ',
    'Antec P5 Black mATX Silent Chassis, 1 X 120mm/1 x140mm Fans, 1 x HD Audio, USB 3.0 X 2, Sound Dampening                  ',
    'Antec Dark Phantom 301M MicroATX Tower, Tempered Glass, ARGB, 120mm Fan, Upto 280mm Radiator, MicroATX/Mini-ITX          ',
    'SilverStone SST-PS16B Mini Tower Computer Chassis, MicroATX/Mini-ITX,120mm Fan,1x Audio, 1x Mic, 2x USB 3.0, Black       ',
    'Antec VSK2000-U3 Black micro-ATX/ITX Slim SoHo Desktop/Tower Case USB3.0 TFX PSU                                         ',
    'Thermaltake S100 TG Snow, Tempered Glass Micro Chassis, 120mm Fan, USB 3.0, USB 2.0, mATX/mITX         ',
    'Tecware Forge M, Black, MicroATX Tower w/ Tempered Glass Window, 4x 120mm Fans, USB 3.0, mATX/mITX         ',
    'Cooler Master MasterBox MB320L, Black, Mini Tower Chassis, Tempered Glass, 120mm Fan, USB 3.2, Micro-ATX/Mini-ITX        ',
    'CiT Flash, MicroATX Case, with Tempered Glass Window, Black, 4x 120mm ARGB LED Fans, Micro-ATX/Mini-ITX           ',
    'Fractal Design Core 1000, Black, Mini Tower Computer Case, 1x 120mm Silent Series R2 Fan, mATX/Mini-ITX/DTX, w/o PSU     ',
    'Thermaltake Versa H18 Black micro-ATX Chassis with Window, MicroATX/Mini-ITX, 120mm Fan, 2x USB 2.0, USB 3.0             ',
    'Thermaltake Versa H17 Black MicroATX Computer Chassis, MicroATX/Mini-ITX, 120mm Fan, 2x USB 2.0, USB 3.0                 ',
    'Thermaltake Versa H15, Black, Mid Tower Gaming Case, 1x 120mm Fan, USB 3.0, 4 Expansion Slots, Micro-ATX/Mini-ITX        ',
    'Thermaltake S100 TG, Tempered Glass Micro Chassis, 120mm Fan, USB 3.0, USB 2.0, mATX/mITX           ',
    'Tecware Nexus M, Black/Red, MicroATX Chassis w/ Tempered Glass Window, 3x 120mm Fans, USB 3.0, mATX/mITX            ',
    'Tecware Nexus M, Black, Mini Tower Case w/Tempered Glass Window, 3x 120mm Fans, USB 3.0, ITX/mATX                       ',
    'Tecware Nexus M, Black & White, Mini Tower Case w/Tempered Glass Window, 3x 120mm Fans, USB 3.0, ITX/mATX                ',
    'Silverstone PS09B, Black, Mini Tower Chassis, 1x 120mm Fan, USB 3.0, Foam Padding, Micro-ATX/Mini-DTX/Mini-ITX     ',
    'Antec VSK10 Mid Tower Computer Chassis, MicroATX/Mini-ITX, 2x USB3.0, 120mm Fan, HD Audio, Mic In, Upto 280mm Radiator   ',
    'Antec NSK3100, Black, Mini Tower Chassis, 1x 92mm Fan, 2x USB 3.0, Micro-ATX/Mini-ITX         ',
    'CiT S503 Slim Desktop Computer Chassis, Micro ATX/Mini ITX, Black, Vertical/Horizontal, Half-Height Slots, with USB 3.0  ',
    'GameMax Expedition, White/Black Gaming MicroATX Computer Chassis, with Window, 1x120mm Blue LED Fan, USB 3.0/USB 2.0     ',
    'GameMax Expedition Chassis, Windowed, 120mm Blue LED Fan Included, Radiator Support, MicroATX/MiniITX, USB 3.0           ',
    'DEEPCOOL MATREXX 30 MicroATX Chassis, Tempered Glass, 1x 120mm Fan, USB 3.0, MicroATX/Mini-ITX                           ',
    'CiT Seven Chassis, RGB Front Panel, Acrylic Window, 1x 120mm Fan, Radiator Support, MicroATX/Mini-ITX                    ',
    'CiT Serenity MicroATX Gaming Chassis, Black,, MicroATX, Mini-ITX, 120mm Fan, HD Audio, Mic In, USB 2.0, USB 3.0          ',
    'CiT Beam Chassis, RGB Front Panel, Acrylic Side Window, 120mm Fan, Radiator Support, MicroATX/Mini-ITX                   ',
    'Antec VSK-3000B-U3 Mid Tower Computer Chassis, MicroATX/Mini ITX, USB 3.0, 2.5" SSD Bay, 92mm Fan Included, Black        ',
    'CiT F3 White/Black Micro ATX/Mini ITX Tower Chassis With 2x120mm Blue LED Fans, USB 3.0, HD Audio, SD/TF Card Reader     ',
    'CiT F3 Black/Red Micro ATX/Mini ITX Tower Chassis With 2x120mm Red LED Fans, USB 3.0, HD Audio, SD/TF Card Reader        ',
    'CiT F3 Black/Purple Micro ATX/Mini ITX Tower Chassis With 2x120mm Purple LED Fans,  USB 3.0, HD Audio, SD/TF Card Reader ',
    'CiT F3 Black/Green Micro ATX/Mini ITX Tower Chassis With 2x 120mm Green LED Fan,  USB 3.0, HD Audio, SD/TF Card Reader   ',
    'CiT Coach MicroATX Case, MicroATX, Mini-ITX, HD Audio, Mic In, USB 2.0, USB 3.0    ',
    'DEEPCOOL Wave V2 micro-ATX Tower Chassis, Black, MicroATX/Mini-ITX, 2x USB 3.0                                           ',
    'DEEPCOOL Smarter Mini Tower Computer Chassis, Black, MicroATX/Mini-ITX, USB 3.0                                          ',
    'CiT Work MicroATX Case, MicroATX, Mini-ITX, HD Audio, Mic In, USB 2.0, USB 3.0         ',
    'Corsair Crystal 280X RGB White MicroATX PC Case w/ Tempered Glass Window, MicroATX/Mini-ITX, 2x120mm Light Loop RGB Fans ',
    'Corsair Crystal 280X RGB Black MicroATX PC Case w/ Tempered Glass Window, MicroATX/Mini-ITX, 2x120mm Light Loop RGB Fans ',
    'Thermaltake Level 20 VT Cube micro-ATX/ITX, Black, USB 3.0 x 2,USB 2.0 x 2, 4mm Tempered Glass Panels x 4                ',
    'GameMax Kamikaze Pro ARGB Chassis, MicroATX/MiniITX, Glass Side Panel, 4x Dual-Ring Halo ARGB Fans, 2x USB3.0, 2x USB2.0 ',
    'Cooler Master MasterBox Q300L, Black, Mini Tower Computer Chassis, w/ Window, micro-ATX/Mini-ITX, 120mm Fan, USB 3.0     ',
    'Fractal Design Core 1100, Black, Mini Tower Chassis, 1x 120mm Fan, USB 3.0, Mini-ITX/Micro-ATX, w/o PSU              ',
    'Thermaltake Versa H15 Micro ATX Gaming Case, micro-ATX, Windowed, USB 3.0, 120mm Fan, Black                              ',
    "ScanFX Mining Case Aluminum Open Air Free Standing for upto 8 GPU's and 5 x 120mm Fans and upgradable to rack & stack    ",
    'Cooler Master Vertical GPU Holder & Riser Cable, 1 GPU per Holder, 7 PCI Case Slots Required, Dark Metallic Grey         ',
    'SilverStone 5.25" Front Panel Multi-functional Internal Card Reader, LCD Displays, 1x USB 3.1 Gen1 C, 2x USB 3.1 Gen1 A  ',
    'Silverstone ES02-USB 2.4GHz Wireless Eemote PC power/reset switch, USB 2.0 9-Pin interface              ',
    'NZXT HUE 5.25" RGB Color Changing LED Controller 5.25" Bay                                                        ',
    'Xclio 3.5" Internal All in One Memory Card Reader, MS/MS Duo, SD/MMC, CF, XD, T-Flash, M2, USB2.0, Black               ',
    'CiT Jetstream PC Gaming Computer Chassis, mITX/mATX/ATX, 1x USB 3.0/2.0, with 500w PSU, Black/Silver Stripe              ',
    'Thermaltake V200 Tempered Glass Mid Tower RGB Gaming Case + Tt 550W Super Silent PSU + 3x 120mm RGB Fans All Fitted      ',
    'CiT Classic PC Chassis + Power Supply, 500W Single Rail PSU, 80mm Fan Included, ATX/MicroATX/MiniITX, USB 3.0            ',
    'Silverstone GD07B Grandia Series Black HTPC & Home Server Desktop Case with USB 3.0, ATX & eATX SSi EEB w/o PSU          ',
    'Cooler Master Vertical GPU Holder & Riser Cable, 1 GPU per Holder, 7 PCI Case Slots Required, Dark Metallic Grey         ',
    'SilverStone 5.25" Front Panel Multi-functional Internal Card Reader, LCD Displays, 1x USB 3.1 Gen1 C, 2x USB 3.1 Gen1 A  ',
    'Silverstone ES02-USB 2.4GHz Wireless Eemote PC power/reset switch, USB 2.0 9-Pin interface              ',
    'NZXT HUE 5.25" RGB Color Changing LED Controller 5.25" Bay                                                        ',
    'Xclio 3.5" Internal All in One Memory Card Reader, MS/MS Duo, SD/MMC, CF, XD, T-Flash, M2, USB2.0, Black               ',
    'ThermalTake Level 20, Super PC Chassis,  E-ATX ,mATX mITX, 3x140mm w/ RGB, USB 3.1 Type-C                                ',
    'Thermaltake View 91 Super PC Chassis, XL-ATX/E-ATX/ATX/mATX/mITX, Tempered Glass, RGB, 4x 140mm RGB Fans, USB 3.1 Type-C ',
    'Lian Li V3000WX, Black, Full Tower Chassis w/ Tempered Glass Window, 4x Fans, USB 3.0 Type-C, E-ATX/ATX/mATX/mITX       ',
    'Thermaltake A700 Aluminium, Full Tower Chassis w/ Tempered Glass Windows, 2x 140mm Fans, E-ATX/ATX/mATX/mITX             ',
    'ASUS ROG Strix Helios White Edition, Mid Tower PC Case, ARGB, Tempered Glass, 4x 140mm Fans, E-ATX/ATX/Micro       ',
    'Antec TORQUE, White, Aluminium Open-Frame Mid Tower PC Chassis, w/ Tempered Glass Windows, E-ATX~mITX, USB3.1 Type-C     ',
    'Antec TORQUE, Black/Red, Aluminium Open-Frame Mid Tower PC Chassis, w/ Tempered Glass Windows, E-ATX~mITX, USB3.1 Type-C ',
    'DEEPCOOL GamerStorm NEW ARK 90, Full Tower RGB PC Case, TG Windows, E-ATX~mITX, 280mm Captain AIO Cooler,4x140mm RGB Fan ',
    'Thermaltake Level 20 GT RGB Plus, Black, Full Tower Chassis with Window/s, ATX E-ATX MicroATX Mini-ITX, 3 x Riing Fans   ',
    'Thermaltake AH T600 Snow, Tempered Glass Full Tower Chassis, Tempered Glass, USB 3.0, USB Type-C, E-ATX/ATX/mATX/mITX    ',
    'Thermaltake View 71 Full Tower Chassis, Tempered Glass, RGB, 4x 120mm RGB Fans, USB 3.1 Type-C, E-ATX/ATX/mATX/mITX      ',
    'Thermaltake AH T600, Tempered Glass Full Tower Chassis, Tempered Glass, USB 3.0, USB Type-C, E-ATX/ATX/mATX/mITX         ',
    'Phanteks Enthoo G.Silver EVOLV ATX Tempered Glass Edition                ',
    'ThermalTake The Tower 900 Super Tower Computer Chassis, Full Side Windows, 2x 140mm Turbo Fans, 4x USB 3.0, w/o PSU      ',
    'ThermalTake The Tower 900 Super Tower Computer Chassis, Full Side Windows, 2x 140mm Turbo Fans, 4x USB 3.0, w/o PSU      ',
    'Thermaltake Level 20 GT Black Ed. Full Tower Chassis, Tempered Glass, 2x 200mm ARGB Fans/1x 140mm, E-ATX/ATX/mATX/mITX   ',
    'be quiet! Dark Base Pro 900 rev.2, Silver, RGB, Full Tower PC Case, w/ Tempered Glass Window, XL-ATX~mITX, 3x 140mm Fans ',
    'be quiet! Dark Base Pro 900 rev.2, Black, RGB, Full Tower PC Case, w/ Tempered Glass Window, XL-ATX~mITX, 3x 140mm Fans  ',
    'Thermaltake Core P8, Black, Full Tower Chassis w/ Tempered Glass Windows, USB Type-C, E-ATX/ATX/MicroATX/Mini-ITX   ',
    'Fractal Design Define 7 XL, Black, Full Tower w/ Dark Tempered Glass, 3x 140mm Fans, USB 3.1 Type-C, SSI-EEB to Mini-ITX ',
    'Thermaltake View 71 Snow Edition Full Tower Computer Chassis, w/ 4x Tempered Glass Windows, EATX/ATX/mATX/mITX, 2x 140mm ',
    'Fractal Design Define 7 XL, Black Solid, Mid Tower Chassis, 3x 140mm Fans, USB 3.1 Type-C, SSI-EEB to Mini-ITX           ',
    'Corsair Graphite Series 780T White Full Tower Case w/o PSU                                                               ',
    'Corsair Graphite Series 780T Black Full Tower Case w/o PSU                                                               ',
    'Thermaltake View 71 ARGB, Full Tower Chassis w/ 4x Tempered Glass Windows, 3x 140mm ARGB Fans, E-ATX/ATX/mATX/mITX       ',
    'ThermalTake View 51, Black, Full Tower w/ Tempered Glass Window, 2x 200mm, 1x 120mm ARGB Fan, USB 3.0, ATX/MicroATX/mITX ',
    'Thermaltake Level 20 HT, Black, Full Tower Chassis w/ Tempered Glass Window, 2x 140mm Fans, Type-C, E-ATX/ATX/mATX/mITX  ',
    'Thermaltake Level 20 HT Snow, White, Full Tower w/ Tempered Glass Window, 2x 140mm Fans, Type-C, E-ATX/ATX/mATX/mITX     ',
    'ThermalTake Level 20 GT, Black, Full Tower Chassis with Window/s,  ATX E-ATX MicroATX Mini-ITX, 1x140mm Fan,USB 3.0/2.0  ',
    'be quiet! Dark Base 900, Orange, Full Tower Computer Chassis, E-ATX to Mini ITX, with 3x 140mm Silent Wings Fan          ',
    'be quiet! Dark Base 900, Black, Full Tower Computer Chassis, E-ATX to Mini ITX, with 3x 140mm Silent Wings Fans          ',
    'ThermalTake View 51 Snow, White, Full Tower w/ Tempered Glass, 2x 200mm, 1x 120mm ARGB Fan, USB 3.0, ATX/MicroATX/mITX   ',
    'ASUS TUF GT501 White Edition Gaming Mid Tower Case, Tempered Glass, Aura Sync, 4x Fans, USB 3.1, ATX/MicroATX/Mini-ITX   ',
    'Thermaltake View 71 Full Tower Computer Chassis, w/ 4x Tempered Glass Windows, EATX/ATX/mATX/mITX, 2x140mm Blue LED Fans ',
    'Thermaltake Core X5 TG Snow Edition, White, Cube Computer Chassis, E-ATX/ATX/MicroATX/Mini-ITX, w/ Window, 2x 120mm Fans ',
    'Cooler Master NR600P MasterBox, Mid Tower Chassis, 120mm Fan, 2x 140mm Fans, E-ATX/ATX/mATX/mITX/SSI CEB/SSI EEB, Black  ',
    'ThermalTake Core X71 TG Edition Computer Chassis, Tempered Glass, Dual Chamber and Fully Modular, 2x USB 3.0, w/o PSU    ',
    "ScanFX Mining Case Aluminum Open Air Free Standing for upto 8 GPU's and 5 x 120mm Fans and upgradable to rack & stack    ",
    'Fractal Design Define XL R2 Titanium Grey Full Tower Case, 3x Silent Series R2 Fans, USB 3.0, ATX/mATX/mITX/E-ATX/XL-ATX ',
    'Fractal Design Define XL R2 Black Pearl Full Tower Case, 3x Silent Series R2 Fans, USB 3.0, ATX/mATX/mITX/E-ATX/XL-ATX   ',
    'Sahara P75 SYNC Full Tower Gaming Case, Tempered Glass, 6 Pirate Turbo RGB 120mm Quiet Fans, Remote Control, White       ',
    'ASUS TUF Gaming GT501VC, Gaming Mid Tower Case, Tempered Glass Window, 2x USB 3.1 Gen 1, ATX/MicroATX/Mini-ITX/EATX      ',
    'Sahara P75 SYNC Full Tower Gaming Case, Tempered Glass, 6 Pirate Turbo RGB 120mm Quiet Fans, Remote Control, Black       ',
    'Sahara P75 Full Tower Gaming Case, Tempered Glass, 6 Pirate Turbo RGB 120mm Quiet Fans, Remote Control, White            ',
    'GameMax Abyss ARGB, Full Tower Chassis w/ Tempered Glass Window, 120mm ARGB Fan, USB 3.0, ATX/EATX/MicroATX/Mini-ITX     ',
    'ThermalTake S300 Snow Edition, White, Mid Tower w/ Tempered Glass Window, 1x 120mm Fans, USB 3.0, ATX/MicroATX/mITX      ',
    'DEEPCOOL MACUBE 550, White, Full Tower Chassis w/ Tempered Glass Window, 120mm Fan, USB 3.0, ATX/MicroATX/Mini-ITX       ',
    'Corsair Obsidian Series 1000D, Black, Super Tower Computer Chassis, with Tempered Glass Windows, E-ATX/ATX/mATX/mITX/EEB ',
    'be quiet! Dark Base Pro 900 rev.2, Orange, RGB, Full Tower PC Case, w/ Tempered Glass Window, XL-ATX~mITX, 3x 140mm Fans ',
    'Thermaltake View 71 RGB Full Tower Chassis, w/ 4x Tempered Glass Windows, EATX/ATX/mATX/mITX, 3x 140mm RGB Riing Fans    ',
    'Fractal Design Vector RS, BO, Mid Tower w/ Dark Tempered Glass Windows, 3x 140mm Fans, USB Type-C, EATX/ATX/mATX/mITX    ',
    'Fractal Design Vector RS, Blackout, Mid Tower w/Tempered Glass Windows, 3x 140mm Fans, USB Type-C, EATX/ATX/mATX/mITX    ',
    'Corsair Obsidian 750D Airflow Edition Black Full Tower Chassis w/ Window, 3x 140mm Fans, mITX/mATX/ATX/EATX/XLATX        ',
    'Corsair Obsidian 750D Black Full Tower case Aluminium Steel with Side Window 3x140mm Fans USB 3.0 E-ATX/ATX w/o PSU      ',
    "ScanFX Mining Case Aluminum Open Air Free Standing for upto 8 GPU's and 5 x 120mm Fans and upgradable to rack & stack    ",
    'Cooler Master Vertical GPU Holder & Riser Cable, 1 GPU per Holder, 7 PCI Case Slots Required, Dark Metallic Grey         ',
    'SilverStone 5.25" Front Panel Multi-functional Internal Card Reader, LCD Displays, 1x USB 3.1 Gen1 C, 2x USB 3.1 Gen1 A  ',
    'Silverstone ES02-USB 2.4GHz Wireless Eemote PC power/reset switch, USB 2.0 9-Pin interface              ',
    'NZXT HUE 5.25" RGB Color Changing LED Controller 5.25" Bay                                                        ',
    'Xclio 3.5" Internal All in One Memory Card Reader, MS/MS Duo, SD/MMC, CF, XD, T-Flash, M2, USB2.0, Black               ',
    'Silverstone GD07B-C Grandia Series, HTPC & Home Server Desktop Case, USB 3.0 Type-C, E-ATX/ATX/mATX/SSI CEB/SSI EEB    ',
    'Fractal Design Define 7, White, Mid Tower w/ Tempered Glass, 3x 140mm Fans, USB 3.1 Type-C, E-ATX/ATX/mATX/mITX          ',
    'Fractal Design Define 7, Black/White, Mid Tower w/ Tempered Glass, 3x 140mm Fans, USB 3.1 Type-C, E-ATX/ATX/mATX/mITX    ',
    'Fractal Design Define 7, Black, Mid Tower w/ Tempered Glass, 3x 140mm Fans, USB 3.1 Type-C, E-ATX/ATX/mATX/mITX          ',
    'Fractal Design Define 7, White Solid, Mid Tower Chassis, 3x 140mm Fans, USB 3.1 Type-C, E-ATX/ATX/mATX/mITX              ',
    'Fractal Design Define 7, Grey Solid, Mid Tower Chassis, 3x 140mm Fans, USB 3.1 Type-C, E-ATX/ATX/mATX/mITX              ',
    'Fractal Design Define 7, Black/White Solid, Mid Tower Chassis, 3x 140mm Fans, USB 3.1 Type-C, E-ATX/ATX/mATX/mITX        ',
    'Fractal Design Define 7, Black Solid, Mid Tower Chassis, 3x 140mm Fans, USB 3.1 Type-C, E-ATX/ATX/mATX              ',
    'SilverStone GD08B Grandia Desktop HTPC ATX/mATX  Silent High Airflow Performance, Black                 ',
    'Fractal Design Define R6, White, 3x 140mm Fans, E-ATX/ATX/MicroATX/MiniITX, USB 3.1 Gen2 Type-C                          ',
    'Fractal Design Define R6, Black, 3x 140mm Fans, E-ATX/ATX/MicroATX/MiniITX, USB 3.1 Gen2 Type-C                          ',
    'be quiet! SILENT BASE 801 Chassis, Silver, 3x 140mm Fans, Radiator Support, E-ATX/ATX/MicroATX/MiniITX                   ',
    'be quiet! SILENT BASE 801 Chassis, Orange, 3x 140mm Fans, Radiator Support, E-ATX/ATX/MicroATX/MiniITX                   ',
    'be quiet! SILENT BASE 801 Chassis, Black, 3x 140mm Fans, Radiator Support, E-ATX/ATX/MicroATX/MiniITX                    ',
    'Fractal Design Define R6, Blackout, 3x 140mm Fans, E-ATX/ATX/MicroATX/MiniITX, USB 3.1 Gen2 Type-C                       ',
    'be quiet! SILENT BASE 601 Chassis, Silver, 2x 140mm Fans, Radiator Support, E-ATX/ATX/MicroATX/MiniITX                  ',
    'be quiet! SILENT BASE 601 Chassis, Orange, 2x 140mm Fans, Radiator Support, E-ATX/ATX/MicroATX/MiniITX                   ',
    'be quiet! SILENT BASE 601 Chassis, Black, 2x 140mm Fans, Radiator Support, E-ATX/ATX/MicroATX/MiniITX                  ',
    'be quiet! BG006 Silent Base 600, Silver, Mid Tower Gaming Case, 140/120mm Fans, USB 3.0, ATX/mATX/mITX, Silent Design    ',
    'be quiet! BG006 Silent Base 600, Black, Mid Tower Gaming Case, 140/120mm Fans, USB 3.0, ATX/mATX/mITX, Silent Design     ',
    'be quiet! BG005 Silent Base 600, Black/Orange, Mid Tower Gaming Case, 140/120mm Fans, USB 3.0, ATX/Micro-ATX/Mini-ITX    ',
    'Fractal Design Define 7 Compact, Black, Mid Tower Chassis, 1x 120/1x 140mm Fans, USB 3.1 Gen2 Type-C, ATX/mATX/mITX      ',
    'Silverstone GD09B-C Grandia, Black, HTPC Computer Case, 1x 120mm Fan, USB 3.0, USB Type-C, SSI-CEB/ATX/Micro-ATX        ',
    'Cooler Master Silencio S600, Black, Mid Tower PC Case, with Sound-Dampened Steel Panels, ATX/mATX/mITX, 2x 120mm Fans    ',
    'Antec P101 SILENT, Black, Mid Tower, ATX, E-ATX, MicroATX, Mini-ITX, 3x120mm Fans, 140mm Fan, 2x USB3.0, 2x USB2 .0      ',
    'SilverStone GD10B Grandia, Black, Desktop HTPC Case, 3x 120mm Fans, USB 3.0, SSI-CEB/ATX/Micro-ATX, w/o PSU      ',
    'be quiet! Pure Base 600, Silver, Mid Tower Computer Chassis, 140/120mm Pure Wings 2 Fans, USB 3.0, ATX/mATX/mITX         ',
    'be quiet! Pure Base 600, Black, Mid Tower Computer Chassis, 140/120mm Fans, USB 3.0, ATX/Micro-ATX/Mini-ITX              ',
    'Silverstone GD09B Grandia, Black, HTPC Computer Case, 1x 120mm Fan, USB 3.0, SSI-CEB/ATX/Micro-ATX             ',
    'Fractal Design Meshify C Solid, Black, Mid Tower Computer Chassis, ATX/MicroATX/Mini-ITX, 2x 120mm Fans, USB 3.0         ',
    'Fractal Design Define S, Black, Mid Tower PC Gaming Case, 2x 140mm Fans, USB 3.0, ATX/mATX/mITX, Silent Design         ',
    'Fractal Design Define C Mid Tower Computer Chassis, ATX/mATX/mITX, w/ Sound Damping, ModuVent Technology, 2x120mm Fans   ',
    'Corsair Carbide Series 275Q, Black, Mid Tower PC Case, w/ Low Noise Design, ATX/MicroATX/Mini-ITX, 2x 120mm Fans, USB3.0 ',
    'be quiet! Pure Base 500, White, Mid Tower Chassis, 2x 140mm Pure Wings 2 Fans, USB 3.0, ATX/MicroATX/Mini-ITX            ',
    'be quiet! Pure Base 500, Metallic Grey, Mid Tower Chassis, 2x 140mm Pure Wings 2 Fans, USB 3.0, ATX/MicroATX/Mini-ITX    ',
    'be quiet! Pure Base 500, Black, Mid Tower Chassis, 2x 140mm Pure Wings 2 Fans, USB 3.0, ATX/MicroATX/Mini-ITX            ',
    'Corsair Carbide Series 200R Black Mid Tower Compact ATX Performance Case with USB 3.0 w/o PSU                            ',
    'Corsair Carbide Series 100R Silent Edition Mid-Tower Computer Chassis with USB 3.0, Cable Management & Sound Damping     ',
    'GameMax Silent Mid Tower, Black, Computer Chassis /w Sound Proofing, Fan Control, USB 3.0, ATX/Micro-ATX/Mini-ITX       ',
    'Fractal Design Core 2500, Black, Mid Tower Computer Chassis, 2x 120mm Fans, USB 3.0, ATX/Mini ITX/Micro-ATX         ',
    'Corsair 110Q, Black, Mid Tower, 120mm Fan, USB 3.0, ATX/MicroATX/Mini-ITX             ',
    'Antec P7 Silent PC Chassis, 2x 120mm Fans Included, Radiator Support, ATX/MicroATX/MiniITX, USB 3.0                   ',
    'Silverstone PS11B-Q Precision Quiet Black Mid Tower Chassis, with USB 3.0, Foam Padded Side Panels, & 120mm Fan          ',
    'Fractal Design Core 2300 Black Mid Tower Performance Case with USB 3.0 & 2x 120mm Fans w/o PSU                           ',
    'Cooler Master N300 Black Mid Tower Case with 2x 120mm SickleFlow Quiet Fans   ',
    'Thermaltake Versa H21 Mid Tower Computer Chassis, ATX/mATX, 1 x USB 3.0, 1 x 120mm rear exhaust fan, Black               ',
    'Cooler Master MasterBox E500L Red Trim, Mid Tower PC Case, ATX/MicroATX/Mini-ITX, 120mm Fan, USB 3.0, Slide Front Panel  ',
    'Antec VSK-4000B-U3/U2 Mid Tower Case with 120mm Fan and USB 3.0 Port  w/o PSU                                            ',
    'Antec GX200, Black, Mid Tower Computer Chassis, ATX MicroATX Mini-ITX, 120mm Fan, Audio In/Out, 2xUSB 2.0, USB 3.0       ',
    'DEEPCOOL Tesseract BF, Black/Blue, Mid Tower Chassis, 1x 120mm Fan, USB 3.0, ATX/Micro-ATX/Mini-ITX           ',
    'Zalman T6, Black, Mid Tower Computer Chassis, USB 3.0, 2x USB 2.0, ATX/Micro-ATX/Mini-ITX      ',
    'CiT Venom Mesh Mid Tower Gaming Case with Black Interior & 120mm Blue LED Fan                                            ',
    'Fractal Design Define R6 Black, Mid Tower Computer Chassis, E-ATX/ATX/MicroATX/Mini-ITX, 3x 140mm Fans                   ',
    'Corsair Carbide 270R Mid Tower Computer Chassis, ATX/Micro ATX/Mini ITX, with Water Cooling Radiator Support, USB 3.0    ',
    'Antec NSK4100 Black Mid Tower Case with 92mm Quiet Fan                              ',
    'Fractal Design Define 7 XL, Black, Full Tower w/ Dark Tempered Glass, 3x 140mm Fans, USB 3.1 Type-C, SSI-EEB to Mini-ITX ',
    "ScanFX Mining Case Aluminum Open Air Free Standing for upto 8 GPU's and 5 x 120mm Fans and upgradable to rack & stack    ",
    'Thermaltake V200 Tempered Glass Mid Tower RGB Gaming Case + Tt 550W Super Silent PSU + 3x 120mm RGB Fans All Fitted      ',
    'Cooler Master Vertical GPU Holder & Riser Cable, 1 GPU per Holder, 7 PCI Case Slots Required, Dark Metallic Grey         ',
    'SilverStone 5.25" Front Panel Multi-functional Internal Card Reader, LCD Displays, 1x USB 3.1 Gen1 C, 2x USB 3.1 Gen1 A  ',
    'Silverstone ES02-USB 2.4GHz Wireless Eemote PC power/reset switch, USB 2.0 9-Pin interface              ',
    'NZXT HUE 5.25" RGB Color Changing LED Controller 5.25" Bay                                                        ',
    'Xclio 3.5" Internal All in One Memory Card Reader, MS/MS Duo, SD/MMC, CF, XD, T-Flash, M2, USB2.0, Black               ',
    'Thermaltake DistroCase 350P, Black, Mid Tower Open Frame w/ Tempered Glass, Dismantlable Modular Design, ATX/mATX/mITX   ',
    'ASUS ROG Strix Helios, Black, Mid Tower PC Case, with ARGB Lighting & Tempered Glass Windows, E-ATX~mITX, 3x 140mm Fans  ',
    'Thermaltake Core P5 Mid Tower Case, Tempered Glass Edition, Wall Mountable, Dismantlable Modular Design, Black           ',
    'ThermalTake A500 Aluminium TG, Grey, Mid Tower PC Case, w/ Tempered Glass Windows, ATX/mATX/mITX, 3x 120mm Fans, USB-C   ',
    'Fractal Design Define S2 Vision RGB, Mid Tower PC Case, w/ Tempered Glass Windows, E-ATX~mITX, 4x 140mm ARGB Fans, USB-C ',
    'MSI MPG SEKIRA 500X, Black, Full Tower w/ Tempered Glass, 120mm ARGB/4x 200mm (3x ARGB) Fan, Type-C, E-ATX/ATX/mATX/mITX ',
    'Corsair Crystal Series 680X RGB White Dual Chamber Mid Tower PC Case, Tempered Glass Windows, E-ATX~mITX, 3x LL120 Fans  ',
    'Corsair Obsidian 500D RGB SE Mid Tower PC Case w/ Tempered Glass Windows, ATX/mATX/mITX, 3x 120mm Light Loop RGB Fans    ',
    'Fractal Design Define 7 XL, Black, Mid Tower w/ Tempered Glass, 3x 140mm Fans, USB 3.1 Type-C, SSI-EEB to Mini-ITX       ',
    'Cooler Master MasterCase H500M Mid Tower PC Case, w/ Tempered Glass Windows, E-ATX~mITX, 2x 200mm Addressable RGB Fans   ',
    'Corsair Crystal Series 680X RGB Black Dual Chamber Mid Tower PC Case, Tempered Glass Windows, E-ATX~mITX, 3x LL120 Fans  ',
    'MSI MPG SEKIRA 500G, Black/Gold, Full Tower w/ Tempered Glass Window, 120mm/2x 200mm Fans, Type-C, E-ATX/ATX/mATX/mITX   ',
    'Thermaltake Level 20 XT E-ATX Cube Case, mATX, mITX, Black, USB 3.0 x 2,USB 2.0 x 2, 4mm Tempered Glass Panels x 4       ',
    'Fractal Design Define S2 Vision Blackout, Mid Tower PC Case, w/ Tempered Glass Windows, E-ATX~mITX, 4x 140mm Fans, USB-C ',
    'Corsair Crystal Series 570X RGB Premium White Ed Mid Tower Computer Case, ATX/mATX/mITX, Tempered Glass, 3x120mm RGB Fan ',
    'Corsair Crystal Series 570X RGB Mirror Black Tempered Glass Mid Tower PC Case, ATX/mATX/mITX, 3x SP120 RGB Fans, USB3.1C ',
    'Corsair Crystal Series 570X RGB Mid Tower Computer Chassis, ATX/mATX/mITX, Tempered Glass, 3x120mm RGB Fan               ',
    'Corsair Carbide Series 678C Black Mid Tower PC Case, w/ Tempered Glass Window, E-ATX~mITX, 3x 140mm Fans, USB 3.1 C      ',
    'be quiet! Dark Base 700 RGB, Black, Mid Tower PC Case, w/ Tempered Glass Window, EATX-mITX, 2x 140mm SilentWings 3 Fans  ',
    'NZXT H710i, Black/Red, Mid Tower w/ Glass Window, RGB, Smart Control, 4x Fans, USB 3.1 Gen2 Type-C, EATX/ATX/mATX/mITX   ',
    'NZXT H710i, Black, Mid Tower w/ Glass Window, RGB, Smart Control, 4x Fans, USB 3.1 Gen2 Type-C, EATX/ATX/mATX/mITX       ',
    'Thermatake Level 20 RS ARGB Mid Tower Case Tempered Glass Window, 2x 200mm ARGB Fans, 1x 120mm fan, ATX/mATX             ',
    'NZXT H510 Elite, Black, Mid Tower w/ Tempered Glass Windows, 2x ARGB 140mm Fans, USB 3.1 Gen2 Type-C, ATX/mATX/mITX      ',
    'MSI Creator 400M, Black, Mid Tower Chassis w/ Tempered Glass Window, 3x 140mm Fans, USB Type-C, E-ATX/ATX/mATX/mITX      ',
    'Fractal Design Define 7, Grey, Mid Tower w/ Tempered Glass, 3x 140mm Fans, USB 3.1 Type-C, E-ATX/ATX/mATX/mITX          ',
    'Fractal Design Define 7, Black, Mid Tower w/ Dark Tempered Glass, 3x 140mm Fans, USB 3.1 Type-C, E-ATX/ATX/mATX/mITX     ',
    'Cooler Master MasterCase H500P, White, Mid Tower /w Tempered Glass Window, 200mm ARGB Fans, USB 3.2, mITX/mATX/ATX/E-ATX ',
    'Thermaltake AH T200 Snow, Black & White, Mini Tower w/ Tempered Glass Windows, USB Type-C, mATX/mITX   ',
    'Corsair Obsidian Series 500D, Black, Mid Tower PC Case, w/ Tempered Glass Windows, ATX/mATX/mITX, 2x 120mm Fans, USB3.1C ',
    'Corsair Carbide Series SPEC-OMEGA RGB, White, Mid Tower PC Case, Tempered Glass Window, ATX/mATX/mITX, 2x HD120 RGB Fans ',
    'Corsair Carbide Series SPEC-OMEGA RGB, Black, Mid Tower PC Case, Tempered Glass Window, ATX/mATX/mITX, 2x HD120 RGB Fans ',
    'Thermaltake View 37 Mid Tower RGB PC Case, E-ATX/ATX/MicroATX/Mini-ITX, Gull-Wing Side Window, 2x140mm RGB Fans          ',
    'Fractal Design Meshify S2, White, Tempered Glass, 3x 140mm Fans, E-ATX/ATX/MicroATX/MiniITX, USB 3.1 Gen2 Type-C         ',
    'Fractal Design Meshify S2, Black, Tempered Glass, 3x 140mm Fans, E-ATX/ATX/MicroATX/MiniITX, USB 3.1 Gen2 Type-C         ',
    'Fractal Design Meshify S2, Black, Dark Tempered Glass, 3x 140mm Fans, E-ATX/ATX/MicroATX/MiniITX, USB 3.1 Gen2 Type-C    ',
    'Fractal Design Define S2, Gunmetal, Tempered Glass, 3x 140mm Fans, E-ATX/ATX/MicroATX/MiniITX, USB 3.1 Gen2 Type-C       ',
    'Fractal Design Define S2, Blackout, Tempered Glass, 3x 140mm Fans, E-ATX/ATX/MicroATX/MiniITX, USB 3.1 Gen2 Type-C       ',
    'Fractal Design Define S2, Black, Tempered Glass, 3x 140mm Fans, E-ATX/ATX/MicroATX/MiniITX, USB 3.1 Gen2 Type-C          ',
    'be quiet! SILENT BASE 801 Chassis, Silver, Tempered Glass, 3x 140mm Fans, Radiator Support, E-ATX/ATX/MicroATX/MiniITX   ',
    'be quiet! SILENT BASE 801 Chassis, Orange, Tempered Glass, 3x 140mm Fans, Radiator Support, E-ATX/ATX/MicroATX/MiniITX   ',
    'be quiet! SILENT BASE 801 Chassis, Black, Tempered Glass, 3x 140mm Fans, Radiator Support, E-ATX/ATX/MicroATX/MiniITX    ',
    'Thermaltake AH T200, Black, Mini Tower w/ Tempered Glass Windows, USB Type-C, mATX/mITX  ',
    'Fractal Design Define R6, White, Tempered Glass, 3x 140mm Fans, E-ATX/ATX/MicroATX/MiniITX, USB 3.1 Gen2 Type-C          ',
    'Thermaltake View 37 ARGB Ed. Midi Chassis, E-ATX/ATX/MicroATX/Mini-ITX, Gull-Wing Window, 120mm/2x 200mm Fan, USB 3.0    ',
    'Silverstone PM01W-RGB V2 Primera Series White, Mid Tower Computer Chassis, w/ Window, ATX/uATX, 4x140mm Fans, USB 3.0    ',
    'NZXT H710, White, Mid Tower w/ Tempered Glass Window, 3x 120/1x 140mm Fans, USB 3.1 Gen2 Type-C, EATX/ATX/mATX/mITX      ',
    'NZXT H710, Black/Red, Mid Tower w/ Tempered Glass Window, 3x 120/1x 140mm Fans, USB 3.1 Gen2 Type-C, EATX/ATX/mATX/mITX  ',
    'Fractal Design Define R6 Tempered Glass Black, Mid Tower Computer Chassis, E-ATX/ATX/mATX/mITX, 3x 140mm Fans            ',
    'Corsair Carbide Series 678C White Mid Tower PC Case, w/ Tempered Glass Window, E-ATX~mITX, 3x 140mm Fans, USB 3.1 C      ',
    'ASUS TUF GT501 Gaming Mid Tower Case, Tempered Glass, Aura Sync, 3x120/1x140mm Fan, USB 3.1, ATX/MicroATX/Mini-ITX       ',
    'Thermaltake Core P3 Snow Edition Open-air Chassis, Tempered Glass, USB 3.0, ATX/MicroATX/Mini-ITX                        ',
    'Fractal Design Define R6, Gunmetal, Tempered Glass, 3x 140mm Fans, E-ATX/ATX/MicroATX/MiniITX, USB 3.1 Gen2 Type-C       ',
    'Corsair Carbide Series Air 540 High Airflow ATX Cube Case - Direct Airflow Path Cooling For Revolutionary Performance    ',
    'Thermaltake View 32 Mid Tower, Tempered Glass, 3x 120mm RGB Fans, 360mm Radiator Support, ATX/MicroATX/Mini-ITX, USB 3.0 ',
    'MSI MPG SEKIRA 100R, Mid Tower Chassis w/ Tempered Glass Windows, 4x 120mm ARGB Fans, USB Type-C, E-ATX/ATX/mATX/mITX   ',
    'Fractal Design Define R6, Blackout, Tempered Glass, 3x 140mm Fans, E-ATX/ATX/MicroATX/MiniITX, USB 3.1 Gen2 Type-C       ',
    'Fractal Design Define R6, Black, Tempered Glass, 3x 140mm Fans, E-ATX/ATX/MicroATX/MiniITX, USB 3.1 Gen2 Type-C          ',
    'Thermaltake View 21 Mid Tower Chassis, Tempered Glass, RGB, 4x 120mm RGB Fans, USB 3.0, ATX/mATX/mITX       ',
    'Silverstone Primera Series PM01B-RGB, Black, Mid Tower Computer Chassis, w/ Window, ATX/MicroATX, 4x140mm Fans, USB 3.0  ',
    'MSI MPG SEKIRA 100P, Mid Tower Chassis w/ Tempered Glass Windows, 4x 120mm Fans, USB Type-C, E-ATX/ATX/mATX/mITX   ',
    'Corsair iCUE 465X RGB, Black, Mid Tower PC Case w/ Tempered Glass Window, 3x 120mm LL120 RGB Fans, ATX/MicroATX/Mini-ITX ',
    'Corsair iCue 4000X RGB, White, Mid Tower Chassis /w Tempered Glass Window, 3x ARGB Fans, USB 3.1 C, mITX/mATX/ATX/E-ATX  ',
    'Corsair iCue 4000X RGB, Black, Mid Tower Chassis /w Tempered Glass Window, 3x ARGB Fans, USB 3.1 C, mITX/mATX/ATX/E-ATX  ',
    'be quiet! SILENT BASE 601 Chassis, Tempered Glass, Silver, 2x 140mm Fans, Radiator Support, E-ATX/ATX/MicroATX/MiniITX   ',
    'be quiet! SILENT BASE 601 Chassis, Tempered Glass, Orange, 2x 140mm Fans, Radiator Support, E-ATX/ATX/MicroATX/MiniITX   ',
    'be quiet! SILENT BASE 601 Chassis, Tempered Glass, Black, 2x 140mm Fans, Radiator Support, E-ATX/ATX/MicroATX/MiniITX    ',
    'be quiet! BGW07 Silent Base 600, Black/Silver Mid Tower Chassis /w Double-Glazed Window, 140/120mm Fans, ATX/mATX/mITX   ',
    'be quiet! BGW06 (Black) Silent Base 600 Windowed Mid Tower Gaming Case, ATX, 2x USB 2.0 2x USB 3.0, 2x Pure Wings Fans   ',
    'be quiet! BGW05 (Orange) Silent Base 600 Windowed Mid Tower Gaming Case, ATX, 2x USB 2.0 2x USB 3.0, 2x Pure Wings Fans  ',
    'Thermaltake Core P3 TG Open-air Chassis, Tempered Glass, USB 3.0, ATX/MicroATX/Mini-ITX               ',
    'Corsair iCUE 465X RGB, White, Mid Tower PC Case w/ Tempered Glass Window, 3x 120mm LL120 RGB Fans, ATX/MicroATX/Mini-ITX ',
    'Zalman X3, White, Mid Tower Case, with Tempered Glass Window, 4x 120mm ARGB Fans, USB 3.0, ATX/Micro-ATX/Mini-ITX     ',
    'Zalman X3, Black, Mid Tower Case, with Tempered Glass Window, 4x 120mm ARGB Fans, USB 3.0, ATX/Micro-ATX/Mini-ITX     ',
    'Thermaltake H550 ARGB, Mid Tower Chassis w/ Tempered Glass Window, 1x 120mm ARGB Fan, ATX/MicroATX/Mini-ITX              ',
    'Silverstone Seta A1 Titanium Mid Tower Chassis, Tempered Glass, 2x 200mm Fan, 1x 120mm, ATX/mATX/mITX           ',
    'Silverstone Seta A1 Silver Mid Tower Chassis, Tempered Glass, 2x 200mm Fan, 1x 120mm, ATX/mATX/mITX             ',
    'Silverstone Seta A1 Rose Gold Mid Tower Chassis, Tempered Glass, 2x 200mm Fan, 1x 120mm, ATX/mATX/mITX          ',
    'Sahara P75 Full Tower Gaming Case, Tempered Glass, 6 Pirate Turbo RGB 120mm Quiet Fans, Remote Control, Black            ',
    'Sahara P75 Full Tower Gaming Case, Tempered Glass, 6 Pirate Duo Ring RGB 120mm Quiet Fans, Remote Control, Black    ',
    'NZXT H510i, White, Mid Tower w/ Glass Window, RGB, Smart Control, 2x 120mm Fans, USB 3.1 Gen2 Type-C, ATX/mATX/mITX      ',
    'NZXT H510i, Black/Red, Mid Tower w/ Glass Window, RGB, Smart Control, 2x 120mm Fans, USB 3.1 Gen2 Type-C, ATX/mATX/mITX  ',
    'NZXT H510i, Black, Mid Tower w/ Glass Window, RGB, Smart Control, 2x 120mm Fans, USB 3.1 Gen2 Type-C, ATX/mATX/mITX      ',
    'Fractal Design Define 7 Compact, Mid Tower w/ Light Tint Tempered Glass Window, 120/140mm Fan, USB 3.1 C, ATX/mATX/mITX  ',
    'Fractal Design Define 7 Compact, Mid Tower w/ Dark Tint Tempered Glass Window, 120/140mm Fan, USB 3.1 C, ATX/mATX/mITX   ',
    'DEEPCOOL CL500 w/ CF120 PLUS Fans, Black/Silver, Mid Tower Chassis/ TG Window, 3x 120mm ARGB Fans, ATX/MicroATX/Mini-ITX ',
    'Corsair iCUE 220T, White, Mid Tower w/ Tempered Glass Window, 3x 120mm RGB Fans, USB 3.0, ATX/MicroATX/Mini-ITX          ',
    'Corsair iCUE 220T, Black, Mid Tower w/ Tempered Glass Window, 3x 120mm RGB Fans, USB 3.0, ATX/MicroATX/Mini-ITX          ',
    'Cooler Master MasterCase H500 ARGB, Grey, Mid Tower /w Tempered Glass Window, 200/120mm Fans, USB 3.2, EATX/ATX/mATX     ',
    'Cooler Master MasterBox MB530P, Addressable RGB Mid Tower PC Case, Tempered Glass Windows, ATX~mITX, 3x 120mm ARGB Fans  ',
    'be quiet! Pure Base 500DX, White, w/ Tempered Glass Window, 3x 140mm Fans, USB 3.1 Gen2 Type-C, ATX/MicroATX/Mini-ITX    ',
    'be quiet! Pure Base 500DX, Black, w/ Tempered Glass Window, 3x 140mm Fans, USB 3.1 Gen2 Type-C, ATX/MicroATX/Mini-ITX    ',
    'Fractal Design Meshify C TG Light Tint, Mid Tower Computer Chassis, w/ Tempered Glass Window, ATX/mATX/mITX, 2x120mm Fan ',
    'be quiet! Pure Base 600 BGW21, Black, Silent PC Case /w Tempered Glass Window, 140/120mm Fans, USB 3.0, ATX/mATX/mITX    ',
    'be quiet! Pure Base 600 BGW20 Silent Case, Window Edition, Orange                     ',
    'Thermaltake S500 Snow, Tempered Glass Window, 140mm Fan (front), 120mm Fan (Rear), USB 3.0, ATX/MicroATX/Mini-ITX        ',
    'MSI MPG GUNGNIR 110R, Black, Mid Tower Chassis w/ Tempered Glass Window, 4x 120mm ARGB Fans, USB Type-C, ATX/mATX/mITX   ',
    'MSI MPG GUNGNIR 100 Mid Tower Chassis, Tempered Glass, 4x 120mm Fans (1x ARGB), Radiator Support, E-ATX/ATX/mATX/mITX    ',
    'Fractal Design Define C TG, Mid Tower Computer Chassis, with Tempered Glass Window, ATX/MicroATX/Mini-ITX, 2x 120mm Fans ',
    'Deepcool MATREXX 70 3F, Mid Tower, Tempered Glass Windows, 3x120mm ARGB Fans/1x120mm Fan, USB 3.0, E-ATX/ATX/mATX Black  ',
    'ASUS TUF GT301 Gaming Mid Tower Case, Tempered Glass, Aura Sync, 3x120 ARGB/1x120mm Fan, USB 3.2, ATX/MicroATX/Mini-ITX  ',
    'Antec NX800, Mid Tower Chassis w/ Tempered Glass Window, 2x200mm + 1x120mm ARGB Fans, ATX/M-ATX/Mini-ITX, Black          ',
    'Corsair Carbide SPEC-06 RGB, Black, Mid Tower PC Case, Tempered Glass Window, RGB Accent LEDs, ATX~mITX, 2x 120mm Fans   ',
    'Tecware VXR, Black, Dual Chamber Mid Tower Case w/Tempered Glass Windows, 2x USB 3.0, ATX/ITX/mATX                  ',
    'Corsair iCUE 220T RGB Airflow, White, Mid Tower PC Case, w/ Tempered Glass Window, ATX/mATX/mITX, 3x120mm SP120 RGB PRO  ',
    'Corsair iCUE 220T RGB Airflow, Black, Mid Tower PC Case, w/ Tempered Glass Window, ATX/mATX/mITX, 3x120mm SP120 RGB PRO  ',
    'be quiet! Pure Base 500, White, Mid Tower Chassis  w/ Tempered Glass Window, 2 140mm Fans, ATX/MicroATX/Mini-ITX         ',
    'be quiet! Pure Base 500, Metallic Grey, Mid Tower Chassis  w/ Tempered Glass Window, 2 140mm Fans, ATX/MicroATX/Mini-ITX ',
    'Antec NX800, White, Mid Tower w/ Tempered Glass Window, 2x 200mm, 3x 140mm ARGB Fans, USB 3.0, E-ATX/ATX/mATX/mITX      ',
    'Fractal Design Define S Window Edition Black Mid Tower ATX/mATX/mini-ITX Computer Chassis with USB 3.0 + Silent Design   ',
    'Thermaltake View 23 ARGB Mid Tower, Tempered Glass, ARGB, 4x 120mm Fans (3x ARGB), ATX/MicroATX/Mini-ITX                 ',
    'Thermaltake S500 Mid Tower Case Tempered Glass, 120mm + 140mm Fans, USB 3.0, ATX/MicroATX/Mini-ITX                       ',
    'SilverStone RL06BR-GP Red Line, Black/Red ATX Computer Chassis, with Tempered Glass Window, 3x120mm Red LEDs Fans        ',
    'Silverstone PM01CR-W Primera, Mid Tower Computer Chassis, Built in LED Strips, 3x 140mm Fans, mATX/ATX, Matte Black     ',
    'Silverstone PM01BR-W Primera Series, Black, Mid Tower Computer Chassis /w Window, 3x 120mm LED Fans, USB 3.0, ATX/mATX   ',
    'Sahara White P35 Sync RGB Tempered Glass Mid Tower Chassis, 4 x Pirate Turbo RGB Fan             ',
    'Sahara P35 Sync RGB Tempered Glass Mid Tower Chassis 4 x Pirate Turbo RGB Fan Black                             ',
    'Sahara C501, Black, Mid Tower Chassis w/ Tempered Glass Window, 3x 140mm, 1x 120mm Fans, USB 3.0, E-ATX/ATX/mATX/mITX  ',
    'NZXT Source 340 Mid Tower Case "Special Edition" Black + Green Trim, LED Underglow, Tinted Window, USB 3.0               ',
    'Fractal Design Meshify C TG Dark Tint, Mid Tower Chassis, Tempered Glass Window, ATX/mATX 2x120mm Quiet Fans     ',
    'Fractal Design Meshify C TG Clear Mid Tower Case Tempered Glass Window, ATX/mATX 2x 120mm Fan White           ',
    'DEEPCOOL CL500, Black/Silver, Mid Tower Chassis/ Tempered Glass Window, USB 3.0, USB3.1 Type-C, ATX/MicroATX/Mini-ITX    ',
    'Corsair Carbide SPEC-OMEGA, Black/Red, Mid Tower PC Case, w/ Tempered Glass Windows, ATX/mATX/mITX, 120mm Red LED Fan    ',
    'Corsair 4000D, White, Mid Tower w/ Tempered Glass Window, 2x 120mm Fans, USB 3.1 Type-C, mITX/mATX/ATX/E-ATX      ',
    'Corsair 4000D, Black, Mid Tower w/ Tempered Glass Window, 2x 120mm Fans, USB 3.1 Type-C, mITX/mATX/ATX/E-ATX     ',
    'Corsair 4000D Airflow, White, Mid-Tower w/ Tempered Glass Window, 2x 120mm Fans, USB 3.1 Type-C, mITX/mATX/ATX/E-ATX     ',
    'Corsair 4000D Airflow, Black, Mid-Tower w/ Tempered Glass Window, 2x 120mm Fans, USB 3.1 Type-C, mITX/mATX/ATX/E-ATX     ',
    'Cooler Master MasterBox TD500 Mesh, White, Mid Tower /w Tempered Glass Window, 120mm Fans, USB 3.2, mITX/mATX/ATX/E-ATX  ',
    'Cooler Master MasterBox TD500 Mesh, Black, Mid Tower /w Tempered Glass Window, 120mm Fans, USB 3.2, mITX/mATX/ATX/E-ATX  ',
    'be quiet! Pure Base 500, Black, Mid Tower Chassis  w/ Tempered Glass Window, 2 140mm Fans, ATX/MicroATX/Mini-ITX         ',
    'Corsair Carbide Series 275R TG, White, Mid Tower Computer Chassis, w/ Tempered Glass Window, ATX/mATX/mITX, 2x120mm Fans ',
    'SilverStone RL07W-G Redline, White, Mid Tower Gaming Chassis /w Tempered Glass Window, 1x 140mm Fan, USB 3.0, ATX/mATX   ',
    'SilverStone RL06BR-GP Red Line, White/Silver ATX Computer Chassis, with Tempered Glass Window, 3x120mm White LEDs Fans   ',
    'NZXT H500 Overwatch Limited Ed. Compact Mid Tower PC Case, Black/Orange, Tempered Glass Window, ATX/mATX/mITX, 2x 120mm  ',
    'Antec DP502 FLUX, Black, Mid Tower w/ Tempered Glass Window, 3x 120mm ARGB, 2x 120mm Fans, USB 3.0, ATX/mATX/mITX    ',
    'White Sahara P35W RGB Chassis, Tempered Glass, USB 3.0, 4x120mm Fan Included, Radiator Support, ATX/MicroATX/Mini ITX    ',
    'Thermaltake V250 TG ARGB, Mid Tower Chassis, Tempered Glass, 3x 120mm ARGB Fans, 1x 120mm, ATX/mATX  Black               ',
    'Thermaltake H200 Snow Midi Chassis, Tempered Glass, RGB, 120mm Fan, USB 3.0, ATX/MicroATX/Mini-ITX                       ',
    'Thermaltake H200 Midi Chassis, Tempered Glass, RGB, 120mm Fan, USB 3.0, ATX/MicroATX/Mini-ITX                            ',
    'SilverStone RL07B-G-Redline, Black, Mid Tower Gaming Chassis /w Tempered Glass Window, 1x 140mm Fan, USB 3.0, ATX/mATX   ',
    'Silverstone RL06WS-PRO Mid Tower Computer Chassis, Side Window, LED Fan, 2x USB 2.0/2x USB 3.0, Silver/White, ATX/mATX   ',
    'Silverstone RL06 Pro Mid Tower Computer Chassis, Side Window, LED Fan, 2x USB 2.0/2x USB 3.0, Black/Red, ATX/mATX        ',
    'Sahara P35 RGB Chassis, Tempered Glass, USB 3.0, 4x120mm Fan Included, Radiator Support, ATX/MicroATX/Mini ITX           ',
    'NZXT H510, White, Mid Tower Chassis w/ Tempered Glass Window, 2x 120mm Fans, USB 3.1 Gen2 Type-C, ATX/mATX/mITX          ',
    'NZXT H510, Black/Red, Mid Tower Chassis w/ Tempered Glass Window, 2x 120mm Fans, USB 3.1 Gen2 Type-C, ATX/mATX/mITX      ',
    'DEEPCOOL MATREXX 55 V3, Black, Mid Tower w/ Tempered Glass Windows, 3x 120mm ARGB Fans, USB 3.0, E-ATX/ATX/mATX/mITX     ',
    'DEEPCOOL MATREXX 55 V3 ADD-RGB 3F, White, Mid Tower w/ TG Window, 3x 120mm ARGB Fans, USB 3.0, ATX/E-ATX/mATX/Mini-ITX   ',
    'Corsair Carbide SPEC-06 Mid Tower PC Case, Tempered Glass Window, Red Accent Lighting, ATX~mITX, 2x 120mm Fans Black     ',
    'Corsair Carbide Series 275R TG, Black, Mid Tower Computer Chassis, w/ Tempered Glass Window, ATX/mATX/mITX, 2x120mm Fans ',
    'CoolerMaster MasterBox Lite 5 RGB, Mid Tower PC Case w/ Tempered Glass Window, 3x 120mm RGB Fans, ATX/MicroATX/Mini-ITX  ',
    'Cooler Master MasterBox MB520 ARGB, Black, Mid Tower Chassis, Tempered Glass, 3x 120mm ARGB Fan, E-ATX/ATX/mATX/mITX     ',
    'Antec NX600 Mid Tower PC Case, w/ Tempered Glass Front+Side Windows, ARGB Front Strip, ATX/mATX/mITX, 4x120mm ARGB Fans  ',
    'Antec DF600 FLUX, Black, Mid Tower /w Tempered Glass Window, 5x120mm ARGB Fans, USB 3.0, mITX/mATX/ATX       ',
    'Corsair Carbide Series 275R, White, Mid Tower Computer Chassis, w/ Acrylic Window, ATX/MicroATX/Mini-ITX, 2x 120mm Fans  ',
    'Corsair 275R Airflow, White, Mid Tower PC Case w/ Tempered Glass Window, 3x 120mm Fans, ATX/MicroATX/Mini-ITX            ',
    'GameMax F15G, Black, Mid Tower Chassis w/ Tempered Glass Window, 2x 200mm ARGB Fan, USB 3.0, ATX/EATX/MicroATX/Mini-ITX  ',
    'GameMax F15M Mesh, Black, Mid Tower Chassis w/ Tempered Glass Window, 2x 200mm ARGB Fan, USB 3.0, ATX/EATX/MicroATX/Mini ',
    'Zalman Z7 NEO, Black, Mid Tower Case, with Tempered Glass Window, 4x 120mm RGB Fans, USB 3.0, ATX/Micro-ATX/Mini-ITX     ',
    'GameMax Vengeance, Mid Tower Chassis w/ Tempered Glass Window, 4x 120mm ARGB Fan, USB 3.0, ATX/MicroATX/Mini-ITX       ',
    'GameMax Stratos Mini, MicroATX Chassis w/ Tempered Glass Window, 4x 120mm ARGB Fans, USB 3.0, MicroATX/Mini-ITX         ',
    'GameMax Crusader RGB Mid Tower Chassis, Tempered Glass, 4x ARGB 120mm Fans, Radiator Support, ATX/MicroATX/Mini-ITX      ',
    'Corsair Carbide SPEC-06, White, Mid Tower PC Case, Tempered Glass Window, White Accent Lighting, ATX~mITX, 2x 120mm Fans ',
    'Corsair Carbide Series SPEC-DELTA RGB Mid Tower PC Case, w/ Tempered Glass Windows, ATX/mATX/mITX, 3x 120mm RGB Fans     ',
    'Cooler Master MasterBox MB500, Black, Mid Tower PC Case, w/ Tempered Glass Window, ATX/mATX/mITX, 3x 120mm RGB LED Fans  ',
    'Zalman K1 Rev.A, Black, Mid Tower Case, with Tempered Glass Window, 1x 120mm RGB Fan, 2x USB 3.0, ATX/Micro-ATX/Mini-IT  ',
    'Corsair Carbide 270R Mid Tower Computer Chassis, ATX/Micro ATX/Mini ITX, with Side Window, USB 3.0                       ',
    'Thermaltake View 28 RGB Riing Edition Gull-Wing Window Mid Tower Case                                            ',
    'Thermaltake Versa T35 RGB, Black, Mid Tower w/ Tempered Glass Window, 120mm Fan, USB 3.0 Type-A, ATX/mATX/mITX     ',
    'Thermaltake Versa J24 Mid Tower Chassis, Tempered Glass, ARGB, 4x 120mm Fans, USB 3.0, ATX/MicroATX/Mini-ITX            ',
    'ThermalTake S300, Black, Mid Tower w/ Tempered Glass Window, 1x 120mm Fans, USB 3.0, ATX/MicroATX/mITX                   ',
    'Thermaltake H350 RGB, Black, Mid Tower w/ Tempered Glass Window, 120mm Fan, USB 3.0 Type-A, ATX/mATX/mITX    ',
    'Thermaltake H100 Midi Chassis, Tempered Glass, 120mm Fan, USB 3.0, ATX/MicroATX/Mini-ITX                                 ',
    'NZXT Source 340 Black with Blue Trim Mid Tower Case with USB3 Side Window 2x120mm Quiet Fans w/o PSU                     ',
    'MSI MAG VAMPIRIC 010X, Black, Mid Tower Chassis w/ Tempered Glass Window, 120mm ARGB Fan, ATX/MicroATX/Mini-ITX          ',
    'MSI MAG FORGE 100R, Black, Mid Tower w/ Tempered Glass Window, 3x 120mm (2x ARGB) Fans, USB 3.2 Gen1, ATX/MicroATX/mITX  ',
    'DEEPCOOL MATREXX 50 ADD-RGB 4F, Mid Tower /w Tempered Glass, 4x120mm ARGB Fan, USB 3.0, E-ATX/ATX/mATX/mITX              ',
    'Corsair Carbide SPEC-04 TG, Black/Red, Mid Tower PC Chassis, w/ Tempered Glass Window, ATX/mATX/mITX, 120mm Red LED Fan  ',
    'Corsair Carbide Series 275R, Black, Mid Tower Computer Chassis, w/ Acrylic Window, ATX/MicroATX/Mini-ITX, 2x 120mm Fans  ',
    'Corsair 275R Airflow, Black, Mid Tower PC Case w/ Tempered Glass Window, 3x 120mm Fans, ATX/MicroATX/Mini-ITX            ',
    'CiT Raider RGB, Mid Tower PC Case, with Tempered Glass Windows, ATX/MicroATX/Mini-ITX, 4x 120mm RGB LED Fans, White      ',
    'CiT Air Tempered Glass micro-ATX PC Gaming Case, 4x ARGB Fans, USB3.0, 2x USB2.0, 240mm Radiator Support, Fan Controller ',
    'Antec P82 Flow, Mid Tower Chassis w/ Tempered Glass Window, 4 x 140mm Fans, Airflow, ATX/M-ATX/ITX            ',
    'Corsair Carbide 175R RGB, Black, Mid Tower PC Case, w/ Tempered Glass Window, ATX/MicroATX/Mini-ITX,120mm RGB Fan        ',
    'Zalman S5, White, Mid Tower Case, with Tempered Glass Window, 2x 120mm Fans, USB 3.0, ATX/Micro-ATX/Mini-ITX      ',
    'Zalman S5, Black, Mid Tower Case, with Tempered Glass Window, 2x 120mm Fans, USB 3.0, ATX/Micro-ATX/Mini-ITX      ',
    'SilverStone FARA R1, Black, Mid Tower w/ Tempered Glass Window, 1x 120mm Fan, ATX/MicroATX/Mini-ITX     ',
    'Silverstone FARA B1, Black, Mid Tower w/ Tempered Glass Window, 2x 120mm RGB Fans, USB 3.0, ATX/MicroATX/Mini-ITX       ',
    'GameMax Venus Midi Chassis, Tempered Glass, ARGB, 120mm Fan, USB 3.0, ATX/MicroATX/Mini-ITX           ',
    'GameMax Stealth, Mid Tower Chassis w/ Tempered Glass Window, 3x 120mm ARGB Fan, USB 3.0, ATX/MicroATX/Mini-ITX         ',
    'GameMax Panda, White, Mid Tower Chassis w/ Tempered Glass Window, 120mm ARGB Fan, USB 3.0, ATX/MicroATX/Mini-ITX         ',
    'GameMax Fortress Full Tower Chassis, Tempered Glass, Radiator Support, E-ATX/ATX/MicroATX/Mini-ITX             ',
    'GameMax Black Hole, Mid Tower Chassis w/ Tempered Glass Window, 2x 200mm ARGB Fans, USB 3.0, ATX/MicroATX/Mini-ITX       ',
    'DEEPCOOL MATREXX 70 Mid Tower Chassis, Tempered Glass, 120mm Fan, Radiator Support, E-ATX/ATX/MicroATX/MiniITX           ',
    'DEEPCOOL MACUBE 310, White, Mid Tower Chassis w/ Tempered Glass Window, 120mm Fan, USB 3.0, ATX/MicroATX/Mini-ITX        ',
    'Cooler Master Masterbox K500L Black Mid Tower Computer Chassis, with Window,1x120mm, 2x120mm w/ Red LED Fans, USB3.0     ',
    'Antec NX500, Black, Mid Tower PC Case, w/ Tempered Glass Window & ARGB Front Strip, E-ATX/ATX/mATX/mITX, 120mm ARGB Fan  ',
    'Antec NX300, Mid Tower Chassis w/ Tempered Glass Window, White, 3x 120mm Regular Fans, 120mm ARGB Fan, ATX/M-ATX/M-ITX   ',
    'Antec Dark Phantom DP501 Mid Tower, Tempered Glass, ARGB, 120mm Fan, Upto 360mm Radiator, ATX/MicroATX/Mini-ITX          ',
    'Antec Dark Fleet DF500 RGB, Black, Mid Tower PC Case, w/ TG Side+Plastic Front Window, ATX/mATX/mITX, 3x 120mm RGB Fans  ',
    'Corsair 110R, Black, Mid Tower Tempered Glass Window, 120mm Fan, USB 3.0, ATX/MicroATX/Mini-ITX                          ',
    'CiT Raider RGB, Black, Mid Tower PC Case, with Tempered Glass Windows, ATX/MicroATX/Mini-ITX, 4x 120mm RGB LED Fans      ',
    'CiT Blaze, Mid Tower Gaming Chassis with Window, ATX MicroATX Mini-ITX, 6x120mm w/ Red LEDs Fans, 1xHD Audio             ',
    'CiT Blaze PC Gaming Chassis, Tempered Glass, 6x Blue LED 120mm Fans Inc, 240mm Radiator Support, ATX/mATX/mITX, USB 3.0  ',
    'Zalman M3, Mid Tower Case, with Tempered Glass Window, 1x 120mm White LED Fan, USB 3.0, Micro-ATX/Mini-ITX     ',
    'Thermaltake Versa T25, Black, Mid Tower w/ Tempered Glass Window, 120mm Fan, USB 3.0 Type-A, ATX/mATX/mITX   ',
    'Thermaltake H330, Black, Mid Tower w/ Tempered Glass Window, 120mm Fan, USB 3.0 Type-A, ATX/mATX/mITX     ',
    'Silverstone Raven RV05WB-W, White, Mid Tower Case /w Window, USB 3.0, SSI-CEB/ATX/Micro-ATX       ',
    'Silverstone FARA R1, White, Mid Tower w/ Tempered Glass Window, USB 3.0, ATX/MicroATX/Mini-ITX         ',
    'Silverstone FARA R1 Midi Chassis, Black, 120mm Fan, 2x USB 3.0, ATX/Micro-ATX/Mini-ITX      ',
    'Sahara P35 Chassis, Tempered Glass, USB 3.0, Radiator Support, ATX/MicroATX/Mini ITX                     ',
    'MSI MAG VAMPIRIC 011C AMD Ryzen Edition, Black, Mid Tower Chassis w/ Tempered Glass Window, 120mm RGB Fan, ATX/mATX/mITX ',
    'MSI MAG VAMPIRIC 010 Mid Tower Chassis, Tempered Glass, 1x 120mm ARGB Fan, Radiator Support, ATX/mATX/mITX               ',
    'MSI MAG FORGE 100M, Black, Mid Tower w/ Tempered Glass Window, 3x 120mm (2x RGB) Fans, USB 3.2 Gen1, ATX/MicroATX/mITX   ',
    'DEEPCOOL MATREXX 55 V3 ADD-RGB, White, Mid Tower Chassis w/ Tempered Glass Window, USB 3.0, ATX/E-ATX/MicroATX/Mini-ITX  ',
    'DEEPCOOL MACUBE 310, Black, Mid Tower Chassis w/ Tempered Glass Window, 120mm Fan, USB 3.0, ATX/MicroATX/Mini-ITX        ',
    'Corsair Carbide Series SPEC-05, Black, Mid Tower Computer Chassis, with Window, ATX/MicroATX/Mini-ITX, 120mm Red LED Fan ',
    'Corsair Carbide Series 100R Mid-Tower Computer Chassis with Side-Window, USB 3.0, Cable Management w/o PSU               ',
    'Cooler Master MasterBox Q500L, Black, Mid Tower PC Case w/ Acrylic Side Window, ATX/MicroATX/Mini-ITX, 120mm Fan, USB3.0 ',
    'Cooler Master MasterBox E500L Blue Trim, Mid Tower PC Case, w/ Window, ATX/MicroATX/Mini-ITX, 120mm Blue LED Fan, USB3.0 ',
    'CiT Tornado, Mid Tower Case, with Tempered Glass Window, Black, 4x 120mm ARGB LED Fans, ATX/M-ATX/Mini-ITX               ',
    'CiT Celsius, Mid Tower PC Case, with Tempered Glass Window, Black, 3x 120mm ARGB LED Fans, ATX/MicroATX/Mini-ITX        ',
    'Antec NX400, Mid Tower Chassis w/ Tempered Glass Window, 120mm ARGB Fan, ATX/MicroATX/Mini-ITX             ',
    'Antec NX310, Black, Mid Tower Computer Chassis /w Tempered Glass Side Window, 120mm ARGB Fan, ATX, M-ATX, M-ITX, USB 3.0 ',
    'SilverStone PS14-E, Black, Mid Tower Chassis /w Tempered Glass Window, 140/120mm Fans, USB 3.0, SSI-CEB/ATX/Micro-ATX    ',
    'Fractal Design Focus G, White ATX Computer Chassis, with Window, 2x120mm Silent Fans, USB 3.0/USB2.0                     ',
    'Fractal Design Focus G, Black ATX Computer Chassis, with Window, 2x120mm Silent Fans, USB 3.0/USB2.0                     ',
    'Fractal Design Focus G - Petrol Blue, Blue ATX Computer Case, with Window, 2x120mm Silent White LED Fans, USB3.0/USB2.0  ',
    'Fractal Design Focus G - Mystic Red, Red ATX Computer Chassis, with Window, 2x120mm White Silent LED Fans, USB3.0/USB2.0 ',
    'Fractal Design Focus G - Gunmetal Gray, Grey ATX Computer Chassis, with Window, 2x120mm White LED Fans, USB3.0/USB2.0    ',
    'Zalman S4 Plus, Mid Tower Case, with Acrylic Window, 3x 120mm RGB Fans, USB 3.0, ATX/Micro-ATX/Mini-ITX      ',
    'Silverstone FARA B1 Midi Chassis, Tempered Glass, 120mm Fan, USB 3.0, ATX/MicroATX/Mini-ITX      ',
    'Sahara P10 Sync RGB Tempered Glass Mid Tower Chassis 1 x Pirate Turbo RGB Fan                    ',
    'MSI MAG VAMPIRIC 010M, Black, Mid Tower Chassis w/ Tempered Glass Window, 120mm RGB Fan, ATX/MicroATX/Mini-ITX           ',
    'DEEPCOOL MATREXX 55 V3 ADD-RGB, Black, Mid Tower Chassis w/ Tempered Glass Window, USB 3.0, ATX/E-ATX/MicroATX/Mini-ITX  ',
    'Cooler Master MasterBox MB600L, Gunmetal, Mid Tower PC Chassis, with Window + ODD Bay, ATX/MicroATX/Mini-ITX, 120mm Fan  ',
    'CiT Omega, Mid Tower Case w/ Tempered Glass Window, 1x 120mm ARGB Fan, USB 3.0, 2x USB 2.0, Micro-ATX/Mini-ITX   ',
    'CiT C1007 Mid Tower Chassis, Tempered Glass, 120mm RGB Fan, Radiator Support, ATX/MicroATX/Mini-ITX               ',
    'Antec NX300, Mid Tower Chassis w/ Tempered Glass Window, Black, 120mm ARGB Fan, ATX/MicroATX/Mini-ITX               ',
    'Antec GX202, Black, Mid Tower Chassis With Window, ATX/ MicroATX/ Mini-ITX, 2x120mm White LED Fans, 120mm Fan, 2x USB3.0 ',
    'CiT Volcano, Mid Tower Case, with Tempered Glass Window, Black, 4x 120mm ARGB LED Fans, ATX/M-ATX/Mini-ITX     ',
    'ThermalTake Versa J21 TG, Black, Mid Tower Computer Chassis, w/ Tempered Glass Window, ATX/MicroATX/Mini-ITX, 120mm Fan  ',
    'GameMax White Diamond, Mid Tower Chassis w/ Tempered Glass Window, 120mm ARGB Fan, USB 3.0, ATX/MicroATX/Mini-ITX        ',
    'DEEPCOOL MATREXX 55 RGB Compact Mid Tower Dual Tempered Glass Chassis, Radiator Support, E-ATX/ATX/ USB 3.0              ',
    'DEEPCOOL MATREXX 55 Mesh, Black, Mid Tower Chassis w/ Tempered Glass Window, USB 3.0, E-ATX/ATX/MicroATX/Mini-ITX        ',
    'Antec NX220 ARGB, Mid Tower Chassis w/ Side Window, Black, 120mm x ARGB Fan, USB 3.0, ATX/M-ATX/M-ITX              ',
    'Zalman S2, Mid Tower Case, with Acrylic Window, 3x 120mm RGB Fans, USB 3.0, 2x USB 2.0, ATX/Micro-ATX/Mini-ITX      ',
    'Versa H27 Tempered Glass Edition, Black, Mid Tower Computer Chassis, USB 3.0, 120mm Fan Included                         ',
    'ThermalTake Versa H21, Black, Mid Tower Chassis w/ Side Window, 120mm Fan, USB 3.0, Micro-ATX/ATX                ',
    'DEEPCOOL Tesseract SW-WH, White/Black, Mid Tower Chassis /w Side Window, 1x 120mm Blue LED Fan, USB 3.0, ATX/mATX/mITX   ',
    'DEEPCOOL MATREXX 50, Black, Mid Tower Chassis w/ Tempered Glass Windows, 120mm Fan, USB 3.0, E-ATX/ATX/MicroATX/Mini-ITX ',
    'DEEPCOOL E-SHIELD Mid Tower Chassis, Black, Tempered Glass, 120mm Fan, Radiator Support, E-ATX/ATX/MicroATX/MiniITX      ',
    'CiT Sauron ARGB Gaming, Mid Tower Case, with Tempered Glass Window, Black, 120mm ARGB LED Fan, ATX/M-ATX/Mini-ITX        ',
    'CiT Pyro Gaming, Mid Tower Case, with Tempered Glass Window, Black, 120mm ARGB LED Fan, ATX/M-ATX/Mini-ITX      ',
    'CiT Prism Black Mid Tower Computer Chassis, with Side Window, ATX/mATX/m-ITX, 2x 120mm RGB LED Fans, 1x HD Audio, 3x USB ',
    'CiT Master Gaming, Mid Tower Case, with Tempered Glass Window, Black, 2x 120mm ARGB LED Fans, ATX/M-ATX/Mini-ITX        ',
    'CiT C6063 Mid Tower Chassis, Acrylic Window, 120mm RGB Fan, Radiator Support, ATX/MicroATX/Mini-ITX                      ',
    'Antec NX230 ARGB, Black, Mid Tower Chassis w/ Window, 120mm Fan, USB 3.0, ATX/MicroATX/Mini-ITX          ',
    'CiT C1055 Mid Tower Chassis, Acrylic Window, 120mm RGB Fan, Radiator Support, ATX/MicroATX/Mini-ITX                      ',
    'Thermaltake Versa N21 Mid Tower Computer Chassis, ATX/MicroATX/MiniITX, with Window, USB 3.0, 120mm Fan, Black           ',
    'DEEPCOOL Tesseract SW, Black/Blue, Mid Tower Chassis w/ Window, 2x 120mm Blue LED Fans, USB 3.0, ATX/MICRO ATX/MINI-ITX  ',
    'DEEPCOOL D-Shield V2, Black, Compact Mid Tower Chassis /w Window, 1x 120mm Fan, USB 3.0, ATX/mATX/mITX             ',
    'CiT Engine Windowed PC Gaming Chassis, 1x Halo Ring 120mm Fan, 360mm Radiator Support, ATX/mATX/mITX, USB 3.0            ',
    'CiT Dark Soul Black Mid Tower Computer Chassis, Side Window, ATX/mATX, 1x120mm Fans, 1x 120mm Blue LED Fan, 3x USB       ',
    'Antec NX100 Black/Grey Mid Tower Computer Chassis with Side Window, 120mm Fan, ATX/MicroATX/Mini-ITX, USB 3.0            ',
    'CIT Hero Black Mid Tower Computer Chassis, ATX/Micro ATX/Mini ITX, with 120mm Blue LED Fan, USB 3.0, and Side Window     ',
    'NZXT H710i, White, Mid Tower w/ Glass Window, RGB, Smart Control, 4x Fans, USB 3.1 Gen2 Type-C, EATX/ATX/mATX/mITX       ',
    'NZXT H510 Elite, White, Mid Tower w/ Tempered Glass Windows, 2x ARGB 140mm Fans, USB 3.1 Gen2 Type-C, ATX/mATX/mITX      ',
    'NZXT H710, Black, Mid Tower w/ Tempered Glass Window, 3x 120/1x 140mm Fans, USB 3.1 Gen2 Type-C, EATX/ATX/mATX/mITX      ',
    'Antec P120 Crystal, Mid Tower Chassis w/ Tempered Glass Windows, Black, USB 3.0, ATX/M-ATX/M-ITX                         ',
    'NZXT H510, Black, Mid Tower Chassis w/ Tempered Glass Window, 2x 120mm Fans, USB 3.1 Gen2 Type-C, ATX/mATX/mITX          '
  ];
class _CaseBodyState extends State<CaseBody> {
  
  @override
  Widget build(BuildContext context) {
    final id = Provider.of<MyCart1>(context);
    final String k = 'Case';
    return Scaffold(backgroundColor: Colors.black,
        appBar: AppBar(iconTheme: IconThemeData(color: Colors.black),
          title: Text('Cases',style: TextStyle(color: Colors.black)),
          backgroundColor: Colors.purpleAccent, shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(45)),
        ),
        body: Scrollbar(
            child: ListView.separated(
                itemBuilder: (context, int index) {
                  return GestureDetector(
                      onTap: () => {},
                      child: Card(color: Colors.purpleAccent[700], shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(30)),
                        child: Container(
                            child: ListTile(
                          onTap: () => {
                            id.add(k, cases[index]),
                            Navigator.pop(context)
                            //Navigator.push(context,
                              //  MaterialPageRoute(builder: (context) => Main()))
                          },
                          title: Text(cases[index]),
                          subtitle: Text(k),
                        )),
                      ));
                },
                shrinkWrap: true,
                separatorBuilder: (BuildContext context, int index) =>
                    Divider(),
                itemCount: cases.length)));
  }
}
