import 'buildpc.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'cartmodel.dart';

class PsuMain extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return PsuBody();
  }
}

class PsuBody extends StatefulWidget {
  @override
  _PsuBodyState createState() => _PsuBodyState();
}
 final List<String> psu = [
    '800W PCICase M1D2-5800V0V Short Industrial Redundant PSU, 80 PLUS Gold, Single Rail, 66A +12V, 2/3U Industrial',
    '600W SilverStone Gemini GM600-G, 80 PLUS Gold, Fully Wired, Single Rail, 49A, 4x 40mm Fans, ATX, Mini Redundant PSU    ',
    '550W Silverstone Gemini ST55GF, Single Rail, 41A +12V, 2x 40mm Fan, PS/2 Mini redundant, 50 dBA           ',
    '500+500W SilverStone Gemini GM500-G, 80PLUS Gold, Fully Wired, Single Rail, 41A, 4x 40mm Fans, ATX, Mini Redundant PSU   ',
    '1300W Intel AXX1300TCRPS, 80PLUS Titanium, Common Redundant Rackmount PSU                           ',
    '1100W Intel AXX1100PCRPS, 80PLUS Platinum, Common Redundant Rackmount PSU                       ',
    '700W Logic Case SC-SG2U700, Fully Wired, 80 PLUS Bronze, Dual Rail, 25A +12V, 2x 60mm Fans, 2U Industrial   ',
    '600W Logic Case SC-SG2U600, 80 PLUS Bronze, Fully Wired, Dual Rail, 20A +12V, 2x60mm Fan, 2U Industrial          ',
    'Logic Case SC-SG2U500 Single 2U 500W Server 80Plus PSU                           ',
    '400W Logic Case SC-SG2U400, Fully Wired, Single Rail, 2x 60mm Fans, 2U Industrial    ',
    '700W Logic Case SC-SG1U700, 80 PLUS Bronze, Fully Wired, Dual Rail, 27A +12V, 2x40mm Fan, 1U Industrial              ',
    '600W Logic Case SC-SG1U600, 80 PLUS Bronze, Fully Wired, Dual Rail, 40A +12V, 40mm Fan, 1U Industrial             ',
    '500W Logic Case SC-SG1U500, 80 PLUS Bronze, Fully Wired, Dual Rail, 18A +12V, 2x40mm Fan, 1U Industrial             ',
    '350W Logic Case SC-SG1U350, Fully Wired, Single Rail, 16A +12V, 2x40mm Fan, 1U Industrial              ',
    '320W Logic Case SC-FLEX1U320+, 80 PLUS Bronze, Single Rail, 15A +12V, 1x 140mm Fan, 1U Flex ATX       ',
    '300W Seasonic SSP-300SUB FLEX SUB PSU, 80PLUS Bronze, Fully Modular, Dual Rail, 18A, +12V, 1U      ',
    '320W Logic Case SC-FLEX1U320, Single Rail, 15A +12V, 1x 140mm Fan, 1U Flex ATX        ',
    '420W Supermicro Xeon PSU 12v EPS see Specs         ',
    '250W Seasonic SSP-250SUB FLEX SUB PSU, 80PLUS Bronze, Fully Modular, Dual Rail, 12A, +12V, 1U',
    '300W be quiet! TFX Power 2, 80 PLUS Gold, Fully Wired, Dual (2) Rail, 1x80mm Fan, TFX PSU                                ',
    '300W Silverstone SST-TX300, 80PLUS Bronze, Fully Wired, Dual Rail, 29A +12V, 1x80mm Fan, TFX PSU                         ',
    '300W Seasonic SSP-30300 TBS, Full Wired, 80PLUS Bronze, Dual Rail, 21A, TFX, PSU',
    '800W SilverStone SX800-LTI v1.2, Fully Modular, 80 Plus Titanium, Single Rail, 66A, 120mm Fan, SFX PSU     ',
    '700W SilverStone SX700-LPT v1.1 SFX-L Series, Fully Modular, 80 PLUS Platinum, Single Rail, 58.4A, 120mm Fan, SFX-L  ',
    '450W SilverStone NJ450-SXL Nightjar Fanless PSU, 80 PLUS Platnium, Fully Modular, Single Rail, 37.5A, +12V        ',
    '600W Corsair SF600, Fully Modular, 80 PLUS Platinum, SLI/CrossFire, Single Rail, 50A, 92mm Fan, SFX PSU                  ',
    '650W Seasonic Focus SGX, Full Modular, 80 PLUS Gold, SLI/CrossFire, Single Rail, 54A, 120mm Fan, SFX-L PSU w/ATX Adapter ',
    '700W Silverstone SFX-L Series SST-SX700-LPT, Modular, 80PLUS Platinum, SLI/CrossFire, EPS 12V, 120mm Fan, SFX-L PSU      ',
    '600W Corsair SF600 High Performance, 80PLUS Gold, Full Modular, SLI/CrossFire, Single Rail, 50A +12V, EPS 12V, 92mm Fan  ',
    '500W SilverStone FX500-G Flex Series, Fully Wired, 80 PLUS Gold, Single Rail, 41.67A, 40mm Fan, Flex ATX  ',
    '650W SilverStone SX650-G v1.1 SFX Series, Fully Modular, 80 PLUS Gold, Single Rail, 54.2A, 92mm Fan, SFX ',
    '600W be quiet! SFX-L, Full Modular, 80 PLUS Gold, Single Rail, 50A, 120mm Fan, SFX PSU w/ ATX Bracket                   ',
    '500W SilverStone SX500-G v1.1 SFX Series, Fully Modular, 80 PLUS Gold, Single Rail, 41.7A, 92mm Fan, SFX ',
    '500W Seasonic Focus SGX, Full Modular, 80PLUS Gold, Single Rail, 41A, 120mm fan, SFX-L PSU                          ',
    '500W be quiet! SFX-L, Full Modular, 80PLUS Gold, Single Rail, 41.7A, 120mm Fan, SFX PSU w/ ATX Bracket                   ',
    '450W Corsair SF450 High Performance, 80PLUS Gold, Full Modular, SLI/CrossFire, Single Rail, 37A +12V, EPS 12V, 92mm Fan  ',
    '500W SilverStone SX500-LG v2.1 SFX Series, Fully Modular, 80 PLUS Gold, Single Rail, 40A, 120mm Fan, SFX-L ',
    '450W SilverStone SST-ST45SF-G Strider Series PSU, 80 PLUS Gold, Fully Modular, Single Rail, 37.5A, +12V, SFX     ',
    '400W be quiet! SFX Power 2, 80 PLUS Bronze, Fully Wired, Dual (2) Rail, 1x120mm Fan, ATX PSU                             ',
    '450W Silverstone ST45SF v3.0, 80 PLUS Bronze, Fully Wired, Single Rail, 37.5A +12V, 1x 92mm Fan, ATX PSU                 ',
    '350W SilverStone Flex Series FX350-G, Flex ATX Fully Wired, 80PLUS Gold, Single Rail, 29.17A, 40mm Fan, PSU             ',
    '450W SilverStone ST45SF v3.0, Fully Wired, 80 Plus Bronze, Single Rail, 37.5A, 92mm Fan, SFX/ATX PSU       ',
    '300W be quiet! SFX Power 2, 80PLUS Bronze, Fully Wired, Dual (2) Rail, 1x120mm Fan, ATX PSU                           ',
    '300W Silverstone SFX Series ST30SF v2.0, 80PLUS Bronze, Fully Wired, Single Rail, 25A +12V, 1x92mm Quiet Fan             ',
    '300W SilverStone SST-SX300-B SFX Series, 80 Plus Bronze, Fully Wired, Single Rail, 1x 80mm Silent Fan, SFX PSU      ',
    '300W Seasonic SFX SFB, Fully Wired, 80PLUS Bronze, Single Rail, 36A, SFX PSU                       ',
    'Silverstone SFX to ATX PSU Converter, Uniquely offsets SFX PSU, Black                     ',
    '750W Corsair SF750, Full Modular, 80 PLUS Platinum, SLI/CrossFire, Single Rail, 62.5A, 92mm Fan, SFX (w/ATX Bracket) PSU ',
    '650W EVGA SuperNOVA 650GM, Fully Modular, 80 PLUS Gold, Single Rail, 54.1A, 92mm Fan, SFX PSU                            ',
    '450W Corsair SF450, Full Modular, 80 PLUS Platinum, SLI/CrossFire, Single Rail, 37.5A, 92mm Fan, SFX PSU                 ',
    '550W EVGA SuperNOVA 550GM, Fully Modular, 80 PLUS Gold, Single Rail, 45.8A, 92mm Fan, SFX PSU',
    '1600W EVGA SuperNOVA T2, Full Modular, 80PLUS Titanium, SLI/CrossFire, Single Rail, 133.3A, 140mm Fan, ATX PSU           ',
    '1500W be quiet! Dark Power Pro 12, Fully Modular, 80 PLUS Titanium, SLI/CrossFire, Hex Rail, 125A, 135mm Fan, ATX PSU    ',
    '1200W be quiet! Dark Power Pro 12, Fully Modular, 80 PLUS Titanium, SLI/CrossFire, Hex Rail, 100A, 135mm Fan, ATX PSU    ',
    '1200W be quiet! Dark Power Pro 11, Hybrid Modular, 80PLUS Platinum, SLI/CrossFire, Quad Rail, 99A, 135mm Fan, ATX PSU    ',
    '1200W ASUS ROG Thor, Fully Modular, 80PLUS Platinum, SLI/CrossFire, Single Rail, 100A, 135mm Quiet Fan, ATX, PSU         ',
    '1000W EVGA SuperNOVA 1000 T2, Full Modular, 80PLUS Titanium, SLI/CrossFire, Single Rail, 83.3A, 140mm Fan, ATX PSU       ',
    '1000W Seasonic PRIME TX, Full Modular, 80 PLUS Titanium, SLI/CrossFire, Single Rail, 83A, 135mm Fan, ATX PSU             ',
    '1200W Corsair HX1200i, Full Modular, 80PLUS Platinum, SLI/CrossFire, Single Rail, 100A, 140mm Fan, ATX PSU               ',
    '1000W Corsair AX Series AX1000, Full Modular, 80PLUS Titanium, SLI/CrossFire, Single Rail, 83A, 135mm Fan, ATX PSU       ',
    '1000W be quiet! Dark Power Pro 11, Hybrid Modular, 80 PLUS Platinum, SLI/CrossFire, Quad Rail, 83A, 135mm Fan, ATX PSU   ',
    '1000w Antec Signature Titanium, Fully Modular, 80 PLUS Titanium, Single Rail, 83A, 135mm Silent Fan, ATX PSU    ',
    '1000W Seasonic PRIME PX, Full Modular, 80 PLUS Platinum, SLI/CrossFire, Single Rail, 83A, 135mm Fan, ATX PSU             ',
    '1300w Antec Signature Platinum, Full Modular, 80 PLUS Platinium, Single Rail, 108A, 135mm Silent Fan, ATX PSU    ',
    '1000W Corsair HX1000i, 80 PLUS Platinum, Full Modular, SLI/CrossFire, Single/Multi Rail, 83.3A +12V, 140mm Fan, ATX PSU  ',
    '1200W be quiet! Straight Power 11 Platinum, Fully Modular, 80 PLUS Platinum, Quad Rail, 100A, 135mm Fan, ATX PSU         ',
    '1000w Antec Signature Platinum, Full Modular, 80 PLUS Platinium, Single Rail, 83A, 135mm Silent Fan, ATX PSU   ',
    '1000W Corsair HX1000, Full Modular, 80PLUS Platinum, SLI/CrossFire, Single Rail, 83.3A, 135mm Fan, ATX PSU               ',
    '1000W be quiet! Straight Power 11 Platinum, Fully Modular, 80 PLUS Platinum, Quad Rail, 83A, 135mm Fan, ATX PSU          ',
    '1000W be quiet! Straight Power 11, Full Modular, 80PLUS Gold, SLI/CrossFire, Quad Rail, 83.3A, 135mm Fan, ATX PSU        ',
    '1000W Seasonic PRIME GX, Full Modular, 80 PLUS Gold, SLI/CrossFire, Single Rail, 83A, 135mm Fan, ATX PSU                 ',
    '1000W EVGA SuperNOVA 1000 G3, Full Modular, 80PLUS Gold, Quiet SLI/CrossFire, Single Rail, 83.3A, 130mm Fan, ATX PSU     ',
    '1000W EVGA SuperNOVA 1000 G1+, Full Modular, 80 PLUS Gold, SLI/CrossFire, Single Rail, 83.3A, 135mm Fan, ATX PSU         ',
    '1000W Corsair RM1000i, Full Modular, 80PLUS Gold, SLI/CrossFire, Single Rail, 83.3A, 135mm Fan, ATX PSU                  ',
    '1000W Corsair RM1000x, Full Modular, 80PLUS Gold, SLI/CrossFire, Single Rail, 83.3A, 135mm Fan, ATX PSU                  ',
    '1000W Seasonic FOCUS GX, Full Modular, 80 PLUS Gold, SLI/CrossFire, Single Rail, 83A, 120mm Fan, ATX PSU       ',
    '1000W EVGA GQ Series, Hybrid Modular, 80PLUS Gold, SLI/CrossFire, Single Rail, 83.3A, 135mm Fan, ATX PSU                 ',
    '1600W Corsair AXi Series AX1600i, Full Modular, 80 PLUS Titanium, SLI/CrossFire, Single Rail, 133.3A, 140mm Fan, ATX PSU ',
    '1200W Corsair AX1200i, Full Modular, 80PLUS Platinum, SLI/CrossFire, Single Rail, 100.4A, 140mm Fan, ATX PSU             ',
    '1300W EVGA SuperNOVA G2, Full Modular, 80PLUS Gold, SLI/CrossFire, Single Rail, 108.3A, 140mm Fan, ATX PSU               ',
    '1300W Seasonic PRIME, Fully Modular, 80PLUS Gold, SLI/CrossFire, Single Rail, 108A, 135mm Fan, ATX, PSU                  ',
    '1100W Aerocool Strike-X, Hybrid Modular, 80PLUS GOLD 90% Eff, Single Rail, 139mm Quiet Fan, DC-DC ATX PSU',
    '850W Seasonic PRIME TX, Full Modular, 80 PLUS Titanium, SLI/CrossFire, Single Rail, 70A, 135mm Fan, ATX PSU              ',
    '850W Corsair AX Series AX850, Full Modular, 80PLUS Titanium, SLI/CrossFire, Single Rail, 70A, 135mm Fan, ATX PSU         ',
    '850W Corsair HX850i, Full Modular, 80PLUS Platinum, SLI/CrossFire, Single/Multi Rail, 70.8A, 140mm Fan, ATX PSU          ',
    '850W be quiet! Dark Power Pro 11, Hybrid Modular, 80PLUS Platinum, SLI/CrossFire, Quad Rail, 70A, 135mm Fan, ATX PSU     ',
    '850W Seasonic PRIME PX, Full Modular, 80 PLUS Platinum, SLI/CrossFire, Single Rail, 70A, 135mm Fan, ATX PSU              ',
    '850W ASUS ROG-THOR-850P, Full Modular, 80PLUS Platinum, SLI/CrossFire, 71A, 135mm Fan, PSU                               ',
    '850W Thermaltake Toughpower PF1 TT Premium Ed., Full Modular, 80 PLUS Platinum, Single Rail, 120mm Fan, 70A, ATX, PSU   ',
    '850W Seasonic PRIME GX, Full Modular, 80 PLUS Gold, SLI/CrossFire, Single Rail, 70A, 135mm Fan, ATX PSU                  ',
    '850W Corsair HX850, Full Modular, 80 PLUS Platinum, SLI/CrossFire, Single/Multi Rail, 70.8A, 135mm Fan, ATX PSU          ',
    '850W be quiet! Straight Power 11 Platinum, Fully Modular, 80 PLUS Platinum, Quad Rail, 70A, 135mm Fan, ATX PSU           ',
    '850W Seasonic Focus PX-850 80PLUS Platinum, Single Rail, Fully Modular, 70A, 120mm Fan, ATX PSU                          ',
    '850W EVGA SuperNOVA 850 G5, 80 PLUS Gold, SLI/CrossFire, Single Rail, 70.8A, 135mm Fan, ATX PSU                          ',
    '850W Corsair RMx White Series RM850x, Full Modular, 80 PLUS Gold, SLI/CrossFire, Single Rail, 70.8A, 135mm Fan, ATX PSU  ',
    '850W ASUS ROG STRIX 850G White Edition, Full Modular, 80PLUS Gold, SLI/CrossFire, Single Rail, 70A, 135mm Fan, PSU       ',
    '850W be quiet! Straight Power 11, Full Modular, 80PLUS Gold, SLI/CrossFire, Quad Rail, 70.8A, 135mm Fan, ATX PSU         ',
    '850W EVGA SuperNOVA G3, Full Modular, 80 PLUS Gold, SLI/CrossFire, Single Rail, 70.8A, 130mm Fan, ATX PSU                ',
    '850W ASUS ROG STRIX 850G, Full Modular, 80PLUS Gold, SLI/CrossFire, Single Rail, 70A, 135mm Fan, PSU         ',
    '850W EVGA SuperNOVA 850 G1+, Full Modular, 80PLUS Gold, SLI/CrossFire, Single Rail, 70.8A, 135mm Fan, ATX PSU            ',
    '850W NZXT C-Series C850, Fully Modular, 80 PLUS Gold, Single Rail, 70A, 120mm Fan, ATX PSU                ',
    '860W Fractal Design Ion+ 860P, Full Modular, 80 PLUS Platinum, SLI/CrossFire, Single Rail, 71.6A, 140mm Fan, ATX PSU     ',
    '850W Corsair TX-850M, Hybrid Modular, 80PLUS Gold, SLI/CrossFire, Single Rail, 70.8A, 140mm Fan, ATX PSU                 ',
    '850W Thermaltake Toughpower GF1, Full Modular, 80 PLUS Gold, SLI/CrossFire, Single Rail, 70A, 140mm Fan, ATX, PSU   ',
    '850W EVGA GQ Series, Hybrid Modular, 80PLUS Gold, SLI/CrossFire, Single Rail, 70.8A, 135mm Fan, ATX PSU                  ',
    '850W Antec HCG850 Gold, Full Modular, 80PLUS Gold, SLI/CrossFire, Single Rail, 70A, 120mm Fan, ATX PSU                   ',
    '850W Corsair RM Series RM850 (2020), Full Modular, 80 PLUS Gold, SLI/CrossFire, Single Rail, 70.8A, 135mm Fan, ATX PSU   ',
    '850W SilverStone ST85F-GS V2, Fully Modular, 80 Plus Gold, Single Rail, 70.9A, 120mm Fan, ATX PSU     ',
    '850W EVGA BQ Series, Hybrid Modular, 80PLUS Bronze, SLI/CrossFire, Single Rail, 70A, 140mm Fan, ATX PSU                  ',
    '850W DEEPCOOL DQ Series DQ850-M-V2L, Fully Modular, 80PLUS Gold, Single Rail, 70A, 120mm Fan, ATX PSU             ',
    '850W Corsair RMx Series RM850x, Full Modular, 80 PLUS Gold, SLI/CrossFire, Single Rail, 70.8A, 135mm Fan, ATX PSU        ',
    '850W Cooler Master MWE, 80 PLUS Gold Fully Modular PSU, Single Rail, 70.8A +12V, Black, ATX PSU     ',
    '800W CiT FX Pro Series, 80PLUS Bronze, Fully Wired, Single Rail, APFC, 140mm Fan, ATX PSU         ',
    '850W Corsair RM850i, Full Modular, 80PLUS Gold, SLI/CrossFire, Single/Multi Rail, 70.8A, 135mm Fan, ATX PSU              ',
    '850W Seasonic Focus GX 850 80PLUS Gold, Single Rail, Fully Modular, 70A, 120mm Fan, ATX PSU                              ',
    '850W EVGA 850 B5, 80 PLUS Bronze, Fully Modular, ECO Mode, Single Rail, 70.8A + 12V, ATX PSU       ',
    'ThermalTake Dr.Power II PSU Tester with PCI-e SATA Molex CPU 4/8 Pin & 24 pin PSU Connector                              ',
    'Silverstone ES02-USB 2.4GHz Wireless Eemote PC power/reset switch, USB 2.0 9-Pin interface              ',
    '4 Port Veho TA-1 USB World Travel Mains Power Adaptor, 1x 2.4A, 3x 2.1A Fast Charge, for UK/USA/Europe/China/Australia   ',
    'SilverStone ECP01 Dual Output Power Adapter Card with 12V DC jack and 5V USB Type A port, OCP, support             ',
    '2m Scan 3XS Braided Cable Wrap, Flexible, Expandable Sleeve, Black          ',
    '1.8m Scan Power Cable, C14 to C15 Mains Extension Lead, Rubberized, Black   ',
    '15cm Thermaltake Dual 24-pin to 24-pin PSU Adapter Cable, 2x Female to 1x Male, Cryptocurrency/Mining/Gaming             ',
    '50cm Silverstone SST-PP10 Dual 24-pin to 24-pin PSU Adapter Cable, 2x Female to 1x Male, Cryptocurrency/Mining/Gaming    ',
    'Akasa PCI Express 4 Molex Pin to 6 Pin Power cable adaptor (AK-CB4-6)               ',
    '200mm Scan Cable Ties, 100 pack, 200mm x 2.5mm, Black                   ',
    '700W Seasonic PRIME TX Fanless, Full Modular, 80 PLUS Gold, SLI/CrossFire, Single Rail, 58A, ATX PSU       ',
    '600W Seasonic PRIME 600 Titanium Fanless Silent , Full Modular, 80PLUS Titanium, SLI/CrossFire, Single Rail ATX          ',
    '750W Seasonic PRIME TX, Full Modular, 80 PLUS Titanium, SLI/CrossFire, Single Rail, 62A, 135mm Fan, ATX PSU              ',
    '750W Seasonic CONNECT, Full Modular, 80 PLUS Gold, SLI/CrossFire, Single Rail, 62A, 135mm Fan, ATX PSU                  ',
    '750W be quiet! Dark Power Pro 11 Power Supply, Hybrid Modular, 80 PLUS Platinum, 1x135mm, ATX v2.4, PSU                  ',
    '750W Seasonic PRIME PX, Full Modular, 80 PLUS Platinum, SLI/CrossFire, Single Rail, 62A, 135mm Fan, ATX PSU              ',
    '750W Corsair HX750i, 80PLUS Platinum, Full Modular, SLI/CrossFire, Single Rail, 62.5A +12V, 1x140mm Fan, ATX PSU         ',
    '750W Corsair HX Series HX750, 80PLUS Platinum, Full Modular, SLI/CrossFire, Single Rail, 62.5A +12V, 1x135mm Fan, ATX    ',
    '650W be quiet! Dark Power Pro 11 Power Supply, Hybrid Modular, 80PLUS Platinum, 1x135mm, ATX v2.4, PSU                   ',
    '750W Corsair RM750i Series Fully Modular PSU, 80PLUS Gold Certified, 135mm Fan, ATX                                      ',
    '750W Thermaltake Toughpower PF1 TT Premium Ed., Full Modular, 80PLUS Platinum, Single Rail, 120mm Fan, 62A, ATX, PSU   ',
    '600W SilverStone NightJar, Full Modular, 80PLUS Titanium, SLI/CrossFire, Single Rail, 50A,  Fanless, ATX PSU             ',
    '750W Seasonic PRIME GX, Full Modular, 80PLUS Gold, SLI/CrossFire, Single Rail, 62A, 135mm Fan, ATX PSU                   ',
    '750W EVGA SuperNOVA 750 G5, Full Modular 80PLUS Gold, SLI/CrossFire, Single Rail, 62.5A, 135mm Fan, ATX PSU              ',
    '650W Thermaltake Toughpower PF1 TT Premium Ed., Full Modular, 80PLUS Platinum, Single Rail, 120mm Fan, 54A, ATX, PSU    ',
    '750W Seasonic Focus PX-750 80PLUS Platinum, Single Rail, Fully Modular, 62A, 120mm Fan, ATX PSU                          ',
    '750W Corsair RMx White Series RM750x, Full Modular, 80 PLUS Gold, SLI/CrossFire, Single Rail, 62.5A, 135mm Fan, ATX PSU  ',
    '750W be quiet! Straight Power 11 Platinum, Fully Modular, 80 PLUS Platinum, Quad Rail, 62.5A, 135mm Fan, ATX PSU         ',
    '750W ASUS ROG Strix, Fully Modular, 80PLUS Gold, SLI/CrossFire, Single Rail, 62A, 135mm Fan, ATX, PSU                   ',
    '650W Corsair RMi Series RM650i, 80PLUS Gold, Full Modular, SLI/CrossFire, Single Rail, 54A +12V, 1x135mm Fan, ATX PSU    ',
    '750W EVGA SuperNOVA 750 GT, 80 PLUS Gold, Fully Modular, FDB Fan, Single Rail, 62.5A + 12V, ATX PSU      ',
    '750W EVGA SuperNOVA 750 G3, Full Modular, 80 PLUS Gold, SLI/CrossFire, Single Rail, 62.4A, 130mm Fan, ATX PSU            ',
    '750W Corsair RMx Series RM750x, Full Modular, 80PLUS Gold, SLI/CrossFire, Single Rail, 62.5A, 135mm Fan, ATX PSU         ',
    '750W be quiet! Straight Power 11, Full Modular, 80 PLUS Gold, SLI/CrossFire, Quad Rail, 62.5A, 135mm Fan, ATX PSU        ',
    '650W Seasonic Focus PX-650 80PLUS Platinum, Single Rail, Fully Modular, 54A, 120mm Fan, ATX PSU                          ',
    '650W EVGA SuperNOVA P2, 80PLUS Platinum, Full Modular, SLI/CrossFire, Single Rail, 54.1A +12V, 1x140mm Fan, ATX PSU      ',
    '650W SilverStone ST65F-PT v1.1, Fully Modular, 80 Plus Platinum, Single Rail, 54.2A, 120mm Fan, ATX PSU        ',
    '650W be quiet! Straight Power 11 Platinum, Fully Modular, 80 PLUS Platinum, Quad Rail, 54A, 135mm Fan, ATX PSU           ',
    '650W Seasonic PRIME GX, Full Modular, 80 PLUS Gold, SLI/CrossFire, Single Rail, 54A, 135mm Fan, ATX PSU                  ',
    '650W EVGA SuperNOVA 650 GT, 80 PLUS Gold, Fully Modular, Auto Eco Mode, 135mm FDB Fan, 54A + 12V, ATX PSU      ',
    '650W Corsair RMx Series 2018 RM650x, Full Modular, 80PLUS Gold, SLI/CrossFire, Single Rail, 54A, 140mm Fan, ATX PSU      ',
    '650W ASUS ROG Strix, Fully Modular, 80 PLUS Gold, SLI/CrossFire, Single Rail, 54A, 135mm Fan, ATX, PSU                   ',
    '760W Fractal Design Ion+ 760P, Full Modular, 80 PLUS Platinum, SLI/CrossFire, Single Rail, 63.3A, 140mm Fan, ATX PSU     ',
    '750W NZXT C-Series C750, Fully Modular, 80 PLUS Gold, Single Rail, 62A, 120mm Fan, ATX PSU              ',
    '650W be quiet! Straight Power 11, Full Modular, 80 PLUS Gold, SLI/CrossFire, Quad Rail, 54.1A, 135mm Fan, ATX PSU        ',
    '750W Thermaltake Toughpower GF1, Full Modular, 80 PLUS Gold, SLI/CrossFire, Single Rail, 62A, 140mm Fan, ATX, PSU   ',
    '750W EVGA SuperNOVA 750 G1+, Full Modular, 80PLUS Gold, SLI/CrossFire, Single Rail, 62.4A, 135mm Fan, ATX PSU            ',
    '750W Corsair RM Series RM750 (2019), Full Modular, 80 PLUS Gold, SLI/CrossFire, Single Rail, 62.5A, 140mm Fan, ATX PSU   ',
    '750W Antec HCG750 Gold, Full Modular, 80 PLUS Gold, SLI/CrossFire, Single Rail, 62A, 120mm Fan, ATX PSU                  ',
    '660W Fractal Design Ion+ 660P, Full Modular, 80PLUS Platinum, SLI/CrossFire, Single Rail, 55A, 140mm Fan, ATX PSU        ',
    '650W Fractal Design ION SFX-L, Fully Modular, 80PLUS Gold, SLI/CrossFire, Single Rail, 54A, 120mm Fan, SFX-L PSU         ',
    '750W EVGA GQ Series, 80PLUS Gold, Hybrid Modular, SLI/CrossFire, Single Rail, 62.4A +12V, 1x135mm Fan, ATX PSU           ',
    '750W EVGA BQ, 80PLUS Bronze, Hybrid Modular, SLI/CrossFire, Single Rail, 62A +12V, 1x140mm Fan, ATX PSU                  ',
    '750W EVGA 750 B5, 80 PLUS Bronze, Fully Modular, EVGA ECO Mode, Single Rail, 62.5A + 12V, ATX PSU       ',
    '750W DEEPCOOL DQ Series DQ750-M-V2L, Fully Modular, 80 PLUS Gold, Single Rail, 62A, 120mm Fan, ATX PSU               ',
    '750W DEEPCOOL DQ Series DQ750-M-V2L WH, White, Fully Modular, 80 PLUS Gold, Single Rail, 62A, 120mm Fan, ATX PSU        ',
    '750W Corsair Builder CX750M, 80 PLUS Bronze, Hybrid Modular, SLI/CrossFire, Single Rail, 62A +12V, 1x120mm Fan, ATX PSU  ',
    '750W Antec EA750G EarthWatts Gold Pro, Hybrid Modular, 80PLUS Gold, SLI/CrossFire, Single Rai 120mm Fan, ATX, PSU   ',
    '750W Antec EA750G EarthWatts Gold Pro White, Hybrid Modular, 80PLUS Gold, SLI/CrossFire, Single Rai 120mm Fan, ATX, PSU  ',
    '650W Thermaltake Toughpower GF1, Full Modular, 80 PLUS Gold, SLI/CrossFire, Single Rail, 54A, 140mm Fan, ATX, PSU   ',
    '650W Seasonic Focus GX-650 80PLUS Gold, Single Rail, Fully Modular, 54A, 120mm Fan, ATX PSU                              ',
    '650W NZXT C-Series C650, Fully Modular, 80 PLUS Gold, Single Rail, 54A, 120mm Fan, ATX PSU                  ',
    '650W EVGA SuperNOVA 650 G5, Full Modular 80PLUS Gold, SLI/CrossFire, Single Rail, 54.1A, 135mm Fan, ATX PSU              ',
    '650W EVGA SuperNOVA 650 G1+, Full Modular, 80PLUS Gold, SLI/CrossFire, Single Rail, 54A, 135mm Fan, ATX PSU              ',
    '650W EVGA GQ Series, 80PLUS Gold, Hybrid Modular, SLI/CrossFire, Single Rail, 54A +12V, 1x135mm Fan, ATX PSU             ',
    '700W Be Quiet! PURE POWER 11 CM, Semi Modular, 80PLUS Gold, SLI/CrossFire, Dual Rail, 56A, 120mm Fan, ATX PSU            ',
    '650W Corsair TX-M Series TX650M PSU, 80PLUS Gold, Hybrid Modular, Single Rail, 51A + 12V, 120mm Fan, ATX PSU             ',
    'EVGA 650 B5, 80 PLUS Bronze, Fully Modular, EVGA ECO Mode, Single Rail, 54.1A + 12V, FDB Fan, ATX PSU        ',
    '750W SilverStone Strider ST75F-GS v3.0, Fully Modular, 80PLUS Gold, Single Rail, 62.5A, 120mm Fan, ATX PSU               ',
    '750W SilverStone SST-ST75F-PB Strider Plus Series, Fully Modular, 80 PLUS Bronze, Single Rail, 59.2A, 120mm Fan, ATX PSU ',
    '750W Corsair CX750F RGB White, Fully Modular, 80 PLUS Bronze, Single Rail, 62.5A, 120mm Fan, ATX PSU   ',
    '750W Corsair CX750F RGB Black, Fully Modular, 80 PLUS Bronze, Single Rail, 62.5A, 120mm Fan, ATX PSU   ',
    '750W Corsair CX Series CX750, 80PLUS Bronze, Fully Wired, Single Rail, 62.5A +12V, 140mm Fan, ATX PSU                    ',
    '750W Cooler Master MWE, 80 PLUS Gold Fully Modular PSU, Single Rail, 62.5A +12V, Black, ATX PSU      ',
    '700W EVGA BQ, 80PLUS Bronze, Hybrid Modular, SLI/Cross, 120mm DBB Fan, Single Rail, 58.3A + 12V, ATX PSU             ',
    '700W Antec NeoECO ZEN, Fully wired, 80PLUS Gold, SLI/CrossFire, Single Rail, 58A, 120mm Silent Fan, ATX PSU              ',
    '700W  SilverStone ET700-MG Strider Essential Full Modular 80Plus Gold ATX PC Power Supply, Quiet 135mm Fan Flat Cables   ',
    '650W Seasonic Core Gold GM-650 80PLUS Gold, Single Rail, 54A, 120mm Fan, ATX PSU                                         ',
    '650W DEEPCOOL DQ Series DQ650-M-V2L, Fully Modular, 80 PLUS Gold, Single Rail, 54A, 120mm Fan, ATX PSU           ',
    '650W Antec EarthWatts Gold EA650G Pro, Hybrid Modular, 80PLUS Gold, SLI/CrossFire, Single Rail, 54A, 120mm Fan, ATX, PSU ',
    '750W Thermaltake Smart BM2, Full Modular, 80 PLUS Bronze, Single Rail, 62.5A, 140mm Fan, ATX, PSU       ',
    '700W be quiet! System Power 9 CM, Hybrid Modular, 80 PLUS Bronze, SLI/CrossFire, Dual Rail, 56A, 120mm Fan, ATX PSU      ',
    '700W Be Quiet! PURE POWER 11, 80 PLUS Gold, SLI/CrossFire, Dual Rail, 48A, 120mm Fan, ATX PSU                            ',
    '750W Gigabyte AORUS P750W, Full Modular, 80PLUS Gold, SLI/CrossFire, Single Rail, 62A, 135mm Fan, ATX PSU                ',
    '650W Corsair CX650F RGB White, Fully Modular, 80 PLUS Bronze, Single Rail, 54A, 120mm Fan, ATX PSU    ',
    '650W Corsair CX650F RGB Black, Fully Modular, 80 PLUS Bronze, Single Rail, 54A, 120mm Fan, ATX PSU     ',
    '750W Corsair TX-M Series TX750M PSU, 80PLUS Gold, Hybrid Modular, Single Rail, 62A + 12V, 120mm Fan, ATX PSU             ',
    '650W Thermaltake Toughpower GF1, Full Modular, 80 PLUS Gold, SLI/CrossFire, Single Rail, 54.2A, 140mm Fan, ATX, PSU      ',
    '650W SilverStone SST-ST65F-PB Strider Plus Series, Fully Modular, 80 PLUS Bronze, Single Rail, 50.8A, 120mm Fan, ATX PSU ',
    '650W Seasonic Core Gold GC-650 80PLUS Gold, Single Rail, 54A, 120mm Fan, ATX PSU                                         ',
    '650W EVGA BQ, 80 PLUS Bronze, Hybrid Modular, SLI/CrossFire, Single Rail, 54A +12V, 1x140mm Fan, ATX PSU                 ',
    '650W Cooler Master MWE, 80 PLUS Gold Fully Modular PSU, Single Rail, 54.1A +12V, Black, ATX PSU    ',
    '600W be quiet! System Power 9 CM, Hybrid Modular, 80 PLUS Bronze, SLI/CrossFire, Dual Rail, 48A, 120mm Fan, ATX PSU      ',
    '600W Be Quiet! PURE POWER 11 CM, Semi Modular, 80 PLUS Gold, SLI/CrossFire, Dual Rail, 48A, 120mm Fan, ATX PSU           ',
    '750W Fractal Design Integra M 80PLUS Bronze, Hybrid Modular, Single Rail, 62.5A +12V, 1x 120mm Fan, ATX PSU              ',
    '700W be quiet! System Power 9, Full Wired, 80 PLUS Bronze, Dual Rail, 56A, 120mm Fan, ATX PSU                     ',
    '650W Thermaltake Smart BM2, Full Modular, 80 PLUS Bronze, Single Rail, 54A, 140mm Fan, ATX, PSU       ',
    '650W SilverStone Strider Essential ET650-G, Fully Wired, 80PLUS Gold, Single Rail, 53A, 120mm Fan, ATX PSU               ',
    '650W Antec NE650M 80PLUS Bronze, Hybrid Modular, 50A +12V, 120mm Silent Fan, ATX PSU                           ',
    '600W EVGA GD, 80 PLUS Gold, Single Rail, 50A, 120mm Fan, Over Voltage Protection, ATX PSU                            ',
    '600W EVGA 600 BQ, 80PLUS Bronze, Hybrid Modular, SLI/CrossFire, Single Rail, 50A +12V, 1x120mm Fan, ATX PSU              ',
    '600W Be Quiet! PURE POWER 11, 80 PLUS Gold, SLI/CrossFire, Dual Rail, 48A, 120mm Fan, ATX PSU                            ',
    '600W Antec NeoECO ZEN, Fully wired, 80PLUS Gold, SLI/CrossFire, Single Rail, 50A, 120mm Silent Fan, ATX PSU              ',
    '750W SilverStone ET750-B v1.1, Fully Wired, 80 Plus Bronze, Single Rail, 62A, 120mm Fan, ATX PSU        ',
    '750W Cooler Master MWE 750 Bronze V2, Fully Wired, 80 PLUS Bronze, Single Rail, 62.5A, 1x120mm Fan, ATX PSU              ',
    '600W SilverStone Strider Plus, Full Modular, 80 PLUS Bronze, SLI/CrossFire, Single Rail, 46A, 120mm Fan, ATX PSU         ',
    '600W be quiet! System Power 9, Full Wired, 80 PLUS Bronze, Dual Rail, 48A, 120mm Fan, ATX PSU                     ',
    '750W Cooler Master MWE 750 Bronze V2 230v, Fully Wired, 80 PLUS Bronze, Single Rail, 62A, 1x120mm Fan, ATX PSU      ',
    '700W Silverstone T70F-ES230 Strider Series, 80PLUS PSU, Fully Wired, SLI/CrossFire, Single Rail 1x120mm Fan, ATX PSU     ',
    '650W SilverStone ET650-B v1.4, Fully Wired, 80 Plus Bronze, Single Rail, 50A, 120mm Fan, ATX PSU           ',
    '650W Seasonic S12III, Fully Wired, 80PLUS Bronze, Single Rail, 54A, 120mm Fan, ATX PSU                   ',
    '650W Antec NE650C NeoECO Classic, 80 PLUS Bronze, Fully Wired, SLI/CrossFire, Single Rail, 50A +12V, 120mm Fan, ATX PSU  ',
    '600W EVGA 600 BR, Fully Wired, 80 PLUS Bronze, Single Rail, 50A, 120mm Fan, ATX PSU                                      ',
    '700W Cooler Master MWE 700 White V2 Fully Wired, 80PLUS, Single Rail, 58A, 1x120mm Fan, ATX PSU                    ',
    '650W Corsair VS650, Fully Wired, 80 PLUS White, SLI/CrossFire, Single Rail, 52A, 120mm Fan, ATX PSU                      ',
    '650W Corsair CV Series CV650, Fully Wired, 80PLUS Bronze, Single Rail, 54A, 120mm Fan, ATX PSU   ',
    '650W Corsair CV Series CV650, Fully Wired, 80PLUS Bronze, Single Rail, 52A, 120mm Fan, ATX PSU                       ',
    '650W Cooler Master MWE 650 Bronze V2 230v, Fully Wired, 80 PLUS Bronze, Single Rail, 54A, 1x120mm Fan, ATX PSU           ',
    '600W EVGA W2 80 PLUS Fully Wired, Single Rail, 49A + 12V, 1x 120mm Sleeve Bearing Fan, ATX PSU       ',
    '600W Antec VP600 Plus, Fully Wired, , SLI/CrossFire, Dual Rail, 45A, 120mm Fan, ATX PSU                  ',
    '700W CiT FX Pro Series, 80PLUS PSU, Fully Wired, Single Rail, APFC, 140mm Fan, ATX PSU       ',
    '600W Cooler Master MWE 600 V2 White Fully Wired, 80 PLUS, Single Rail, 49A, 1x120mm Fan, ATX PSU Black                   ',
    '600W Silverstone ST60F-ES Strider 80PLUS PSU, Fully Wired, SLI/CrossFire, Single Rail, 46A +12V, 1x120mm Fan, ATX PSU    ',
    '600W CiT FX Pro Series, 80PLUS PSU, Fully Wired, Single Rail, APFC, 140mm Fan, ATX PSU        ',
    '600W Aerocool Cylon, Fully Wired, 80 PLUS White, Single Rail, 45A, 120mm Fan, ATX PSU                                    ',
    '700W Xclio Builder, Fully Wired, 80PLUS Single Rail, 120mm Fan, ATX PSU                           ',
    '600W Xclio Builder, Fully Wired, Single Rail, 120mm Fan, Passive ATX PSU                   ',
    '650W Seasonic PRIME PX, Full Modular, 80 PLUS Platinum, SLI/CrossFire, Single Rail, 54A, 135mm Fan, ATX PSU              ',
    '750W Seasonic Focus GX 750 80PLUS Gold, Single Rail, Fully Modular, 62A, 120mm Fan, ATX PSU                              ',
    '650W EVGA G3, 80PLUS Gold, Full Modular, SLI/CrossFire, Single Rail, 54.1A +12V, 1x130mm Fan, PSU                        ',
    '650W Corsair RM Series RM650 (2019), Full Modular, 80 PLUS Gold, SLI/CrossFire, Single Rail, 54A, 140mm Fan, ATX PSU     ',
    '700W EVGA GD, 80PLUS Gold, Wired Single Rail, 58.3A, 120mm Fan, Over Voltage Protection, ATX PSU                         ',
    '650W Corsair CX650M, 80 PLUS Bronze, Hybrid Modular, SLI/CrossFire, Single Rail, 54A +12V, 1x120mm Fan, ATX PSU          ',
    '650W Corsair CX Series CX650, 80PLUS Bronze, Fully Wired, Single Rail, 54A +12V, 120mm Fan, ATX PSU                      ',
    '700W ThermalTake Smart RGB, Full Wired, 80PLUS, SLI/Crossfire, Single Rail, 54A, 120mm Quiet Fan, ATX, PSU               ',
    '600W Thermaltake Smart RGB, Full Wired, 80PLUS, SLI/Crossfire, Single Rail, 42A, 120mm Fan, ATX, PSU                     ',
    '600W EVGA Fully Wired, 80PLUS SLI/CrossFire, Single Rail, 49A, 120mm Quiet Fan, ATX PSU Black  PSU',
    '550W be quiet! Dark Power Pro 11 Power Supply, Hybrid Modular, 80 PLUS Platinum, 1x135mm, ATX v2.4, PSU                  ',
    '500W Seasonic PRIME Fanless PX, Full Modular, 80 PLUS Platinum, SLI/CrossFire, Single Rail, 41A, ATX PSU              ',
    '550W EVGA SuperNOVA 550 GT, 80PLUS Gold, Fully Modular, Single Rail, 45.8A + 12V, 135mm FDB Fan, ATX PSU       ',
    '550W be quiet! Straight Power 11 Platinum , Fully Modular, 80PLUS Platinum, Quad Rail, 45.8A, 135mm Fan, ATX PSU         ',
    '550W be quiet! Straight Power 11, Full Modular, 80PLUS Gold, SLI/CrossFire, Quad Rail, 45.8A, 135mm Fan, ATX PSU         ',
    '550W ASUS ROG Strix, Fully Modular, 80PLUS Gold, SLI/CrossFire, Single Rail, 45A, 135mm Fan, ATX, PSU                    ',
    '560W Fractal Design Ion+ 560P, Full Modular, 80PLUS Platinum, SLI/CrossFire, Single Rail, 46.6A, 140mm Fan, ATX PSU      ',
    '550W Seasonic Focus GX-550 80PLUS Gold, Single Rail, Fully Modular, 45A, 120mm Fan, ATX PSU                              ',
    '500W Fractal Design ION SFX-L, Fully Modular, 80PLUS Gold, SLI/CrossFire, Single Rail, 41A, 120mm Fan, SFX-L PSU         ',
    '550W EVGA B5, 80 Plus BRONZE, Fully Modular, EVGA ECO Mode, Single Rail, 45.8A +12V, 135mm Fan, ATX PSU            ',
    '550W Corsair TX550M, Hybrid Modular, 80PLUS Gold, SLI/CrossFire, Single Rail, 43A, 120mm Fan, ATX PSU                    ',
    '550W Corsair CX550M, 80 PLUS Bronze, Hybrid Modular, SLI/CrossFire, Single Rail, 45.8A +12V, 1x120mm Fan, ATX PSU        ',
    '550W Antec EarthWatts Gold EA550G Pro, Hybrid Modular, 80PLUS Gold, SLI/CrossFire, Single Rail, 45A, 120mm Fan, ATX, PSU ',
    '550W Corsair CX550F RGB White, Fully Modular, 80 PLUS Bronze, Single Rail, 45.8A, 120mm Fan, ATX PSU   ',
    '550W Corsair CX550F RGB Black, Fully Modular, 80 PLUS Bronze, Single Rail, 45.8A, 120mm Fan, ATX PSU ',
    '550W ThermalTake London, Hybrid Modular, 80PLUS Gold, 140mm Quiet Fan ATX, PSU                                           ',
    '500W Seasonic Core Gold GM-500 80PLUS Gold, Single Rail, 41A, 120mm Fan, ATX PSU                                         ',
    '500W Be Quiet! PURE POWER 11 CM, Semi Modular, 80PLUS Gold, SLI/CrossFire, Dual Rail, 40A, 120mm Fan, ATX PSU            ',
    '550W Thermaltake Smart BM2, Full Modular, 80 PLUS Bronze, Single Rail, 45.5A, 140mm Fan, ATX, PSU        ',
    '500W Seasonic Core Gold GC-500 80PLUS Gold, Single Rail, 41A, 120mm Fan, ATX PSU                                         ',
    '500W EVGA 500 BQ, 80PLUS Bronze, Hybrid Modular, SLI/CrossFire, Single Rail, 41.6A +12V, 1x120mm Fan, ATX PSU            ',
    '500W Antec NeoECO ZEN, Fully wired, 80PLUS Gold, SLI/CrossFire, Single Rail, 42A, 120mm Silent Fan, ATX PSU              ',
    '500W Be Quiet! PURE POWER 11, 80 PLUS Gold, SLI/CrossFire, Dual Rail, 40A, 120mm Fan, ATX PSU                            ',
    '550W Fractal Integra M, Semi-Modular, 80PLUS Bronze, Single Rail, 45.5A, 120mm Fan, ATX PSU        ',
    '550W Antec NE550M 80PLUS Bronze, Hybrid Modular, 42A +12V, 120mm Silent Fan, ATX PSU                               ',
    '500W be quiet! System Power 9 CM, Hybrid Modular, 80PLUS Bronze, SLI/CrossFire, Dual Rail, 38A, 120mm Fan, ATX PSU       ',
    '500W be quiet! BN246 System Power 9, Full Wired, 80PLUS Bronze, Dual Rail, 38A, 120mm Fan, ATX PSU                    ',
    '500W Xclio CRS-C2050-85-08, Fully Wired, 80 PLUS Bronze, Single Rail, 38A +12, 80mm Fan, 2U ATX Server Grade PSU   ',
    '550W Seasonic S12III, Fully Wired, 80PLUS Bronze, Single Rail, 45.5A, 120mm Fan, ATX PSU                 ',
    '550W Cooler Master MWE 550 Bronze V2 230v, Fully Wired, 80 PLUS Bronze, Single Rail, 45A, 1x120mm Fan, ATX PSU         ',
    '500W Seasonic S12III, Fully Wired, 80PLUS Bronze, Single Rail, 40A, 120mm Fan, ATX PSU                         ',
    '500W EVGA GD, 80 PLUSGold, Single Rail, 41.6A, 120mm Fan, Over Voltage Protection, ATX PSU                               ',
    '500W EVGA 500 BR, Fully Wired, 80 PLUS Bronze, Single Rail, 41.7A, 120mm Fan, ATX PSU                                    ',
    '500W Antec VP500 Plus, Fully Wired, Single Rail, 38A, 120mm Fan, 85% Efficiency, ATX PSU                                 ',
    '500W Silverstone Essential , 80PLUS Bronze, Single Rail, 1x120mm, ATX PSU                                  ',
    '500W Aerocool King, Fully Wired, 80PLUS Bronze, Single Rail, 41A, 120mm Fan, ATX PSU                                     ',
    '500W Cooler Master MWE 500 White V2 230V, Fully Wired, 80 PLUS, Single Rail, 41A, 1x120mm Fan, ATX PSU                   ',
    '500W Silverstone Strider Series ST50F-ES230 V2, 80PLUS, Fully Wired, SLI/CrossFire, Single Rail, 34A +12V, 120mm Fan     ',
    '500w CiT ATV Pro 80plus Bronze Fully Wired, Single Rail, 34A +12V, 140mm Fan, ATX PSU        ',
    '500W Aerocool Cylon, Fully Wired, 80PLUS, Single Rail, 37A, 120mm Fan, ATX PSU                                           ',
    '500W Xclio Builder Black , Fully Wired, Single Rail, 120mm Fan, ATX PSU             ',
    '550W Seasonic Focus PX-550 80PLUS Platinum, Single Rail, Fully Modular, 45A, 120mm Fan, ATX PSU                          ',
    '550W Corsair RMx Series 2018 RM550x, Full Modular, 80 PLUS Gold, SLI/CrossFire, Single Rail, 45.8A, 140mm Fan, ATX PSU   ',
    '550W EVGA G3, 80PLUS Gold Full Modular SLI/CrossFire, Single Rail, 45.8A +12V, 1x130mm Fan, PSU                          ',
    '550W Corsair CV Series CV550, Fully Wired, 80PLUS Bronze, Single Rail, 44A, 120mm Fan, ATX PSU                    ',
    '500W Thermaltake Smart RGB, Full Wired, 80PLUS, SLI/Crossfire, Single Rail, 35A, 120mm Quiet Fan, ATX, PSU               ',
    '500W EVGA, 80 PLUS Fully Wired, SLI/CrossFire, Single Rail, 40A +12V, 120mm Fan, ATX PSU                                 ',
    '500W EVGA W2 80PLUS ATX Fully Wired, Single Rail, 40A + 12V, 1x 120mm Sleeve Bearing Fan, ATX PSU                        ',
    '450W Seasonic PRIME Fanless PX, Full Modular, 80 PLUS Platinum, SLI/CrossFire, Single Rail, 37A, ATX PSU',
    '450W be quiet! Straight Power 11, Full Modular, 80PLUS Gold, SLI/CrossFire, Quad Rail, 37.5A, 135mm Fan, ATX PSU         ',
    '450W EVGA SuperNOVA 450GM, Fully Modular, 80PLUS Gold, Single Rail, 37.5A, 92mm Fan, SFX PSU                             ',
    '450W Thermaltake Smart BM2, Full Modular, 80 PLUS Bronze, Single Rail, 37.5A, 140mm Fan, ATX, PSU        ',
    '450W Seasonic FOCUS Gold, Hybrid Modular, 80PLUS Gold, SLI/CrossFire, Single Rail, 37A, 120mm Fan, ATX PSU               ',
    '400W Be Quiet! PURE POWER 11 CM, Semi Modular, 80PLUS Gold, SLI/CrossFire, Dual Rail, 32A,120mm Fan, ATX PSU             ',
    '400W Be Quiet! PURE POWER 11, 80 PLUS Gold, SLI/CrossFire, Dual Rail, 32A, 120mm Fan, ATX PSU                            ',
    '400W be quiet! System Power 9 CM, Hybrid Modular, 80PLUS Bronze, SLI/CrossFire, Dual Rail, 32A, 120mm Fan, ATX PSU       ',
    '450W Corsair CV Series CV450, Fully Wired, 80 PLUS Bronze, Single Rail, 36A, 120mm Fan, ATX PSU                       ',
    '450W Cooler Master MWE 450 Bronze V2 230v, Fully Wired, 80 PLUS Bronze, Single Rail, 37A, 1x120mm Fan, ATX PSU         ',
    '400W be quiet! System Power 9, Full Wired, 80PLUS Bronze, Dual Rail, 32A, 120mm Fan, ATX PSU                             ',
    '300W Be Quiet! PURE POWER 11, 80 PLUS Bronze, Dual Rail, 24A, 120mm Fan, ATX PSU                                  ',
    '400W Silverstone ST40F-ES230 Strider Series, 80PLUS PSU, Fully Wired Single Rail, 1x120mm Fan, ATX PSU                   ',
    '400W Cooler Master MWE 400 White V2 230V, Fully Wired, 80 PLUS, Single Rail, 33A, 1x120mm Fan, ATX PSU                   ',
    '400W CiT FX Pro Series, 80PLUS Bronze, Fully Wired, Single Rail, APFC, 140mm Fan, ATX PSU    ',
    '450W PCICase 80+ ATX PSU     ',
    '450W Corsair CX450M, 80PLUS Bronze, Hybrid Modular, SLI/CrossFire, Single Rail, 37.4A +12V, 1x120mm Fan, ATX PSU         ',
    '350W Seasonic GT ATX, Fully Wired, 80 PLUS Gold, Single Rail, 29A +12V, 120mm Double Ball Bearing Fan, ATX PSU           '
  ];
class _PsuBodyState extends State<PsuBody> {
 
  @override
  Widget build(BuildContext context) {
    final id = Provider.of<MyCart1>(context);
    final String k = 'Power Supply Unit';
    return Scaffold(
        backgroundColor: Colors.black,
        appBar: AppBar(iconTheme: IconThemeData(color: Colors.black),
          title: Text('Power Supplies',style: TextStyle(color: Colors.black)),
          backgroundColor: Colors.orangeAccent,
          shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(45))
        ),
        body: Scrollbar(
            child: ListView.separated(
                itemBuilder: (context, int index) {
                  return GestureDetector(
                      onTap: () => {},
                      child: Card(color: Colors.orangeAccent[400], shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(30)),
                        child: Container(
                            child: ListTile(
                          onTap: () => {
                            id.add(k, psu[index]),
                            Navigator.pop(context),
                           // Navigator.push(context,
                              //  MaterialPageRoute(builder: (context) => Main()))
                          },
                          title: Text(psu[index]),
                          subtitle: Text(k),
                        )),
                      ));
                },
                shrinkWrap: true,
                separatorBuilder: (BuildContext context, int index) =>
                    Divider(),
                itemCount: psu.length)));
  }
}
